// Code generated by ent, DO NOT EDIT.

package devicetelemetry

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the devicetelemetry type in the database.
	Label = "device_telemetry"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// FieldDeviceIdentifier holds the string denoting the device_identifier field in the database.
	FieldDeviceIdentifier = "device_identifier"
	// FieldPropertyName holds the string denoting the property_name field in the database.
	FieldPropertyName = "property_name"
	// FieldValueType holds the string denoting the value_type field in the database.
	FieldValueType = "value_type"
	// FieldValueInt holds the string denoting the value_int field in the database.
	FieldValueInt = "value_int"
	// FieldValueFloat holds the string denoting the value_float field in the database.
	FieldValueFloat = "value_float"
	// FieldValueString holds the string denoting the value_string field in the database.
	FieldValueString = "value_string"
	// FieldValueBool holds the string denoting the value_bool field in the database.
	FieldValueBool = "value_bool"
	// FieldValueJSON holds the string denoting the value_json field in the database.
	FieldValueJSON = "value_json"
	// FieldReceivedAt holds the string denoting the received_at field in the database.
	FieldReceivedAt = "received_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the devicetelemetry in the database.
	Table = "device_telemetry"
)

// Columns holds all SQL columns for devicetelemetry fields.
var Columns = []string{
	FieldTime,
	FieldDeviceIdentifier,
	FieldPropertyName,
	FieldValueType,
	FieldValueInt,
	FieldValueFloat,
	FieldValueString,
	FieldValueBool,
	FieldValueJSON,
	FieldReceivedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// ValueType defines the type for the "value_type" enum field.
type ValueType string

// ValueType values.
const (
	ValueTypeInt    ValueType = "int"
	ValueTypeFloat  ValueType = "float"
	ValueTypeString ValueType = "string"
	ValueTypeBool   ValueType = "bool"
	ValueTypeJSON   ValueType = "json"
	ValueTypeNull   ValueType = "null"
)

func (vt ValueType) String() string {
	return string(vt)
}

// ValueTypeValidator is a validator for the "value_type" field enum values. It is called by the builders before save.
func ValueTypeValidator(vt ValueType) error {
	switch vt {
	case ValueTypeInt, ValueTypeFloat, ValueTypeString, ValueTypeBool, ValueTypeJSON, ValueTypeNull:
		return nil
	default:
		return fmt.Errorf("devicetelemetry: invalid enum value for value_type field: %q", vt)
	}
}

// OrderOption defines the ordering options for the DeviceTelemetry queries.
type OrderOption func(*sql.Selector)

// ByTime orders the results by the time field.
func ByTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTime, opts...).ToFunc()
}

// ByDeviceIdentifier orders the results by the device_identifier field.
func ByDeviceIdentifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceIdentifier, opts...).ToFunc()
}

// ByPropertyName orders the results by the property_name field.
func ByPropertyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPropertyName, opts...).ToFunc()
}

// ByValueType orders the results by the value_type field.
func ByValueType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValueType, opts...).ToFunc()
}

// ByValueInt orders the results by the value_int field.
func ByValueInt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValueInt, opts...).ToFunc()
}

// ByValueFloat orders the results by the value_float field.
func ByValueFloat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValueFloat, opts...).ToFunc()
}

// ByValueString orders the results by the value_string field.
func ByValueString(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValueString, opts...).ToFunc()
}

// ByValueBool orders the results by the value_bool field.
func ByValueBool(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValueBool, opts...).ToFunc()
}

// ByReceivedAt orders the results by the received_at field.
func ByReceivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
