// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// DeviceTelemetry is the predicate function for devicetelemetry builders.
type DeviceTelemetry func(*sql.Selector)

// ModelCategory is the predicate function for modelcategory builders.
type ModelCategory func(*sql.Selector)

// MqttUser is the predicate function for mqttuser builders.
type MqttUser func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// ThingModel is the predicate function for thingmodel builders.
type ThingModel func(*sql.Selector)
