volumes:
  pgdata:
  prometheus-data:
  grafana-storage:
  rabbitmq-data:

networks:
  iot-bridge:
    driver: bridge

services:
  database:
    image: timescale/timescaledb:2.27.0-pg17
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - iot-bridge
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  emqx:
    image: emqx/emqx:5.8.5
    container_name: emqx
    environment:
      EMQX_NODE__NAME: emqx@127.0.0.1
    ports:
      - 1883:1883
      - 8083:8083
      - 18083:18083
    volumes:
      - ./services/emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./services/emqx/etc/acl.conf:/opt/emqx/etc/acl.conf
      - ./services/emqx/etc/certs:/opt/emqx/etc/certs
      - ./services/emqx/data:/opt/emqx/data
      - ./services/emqx/log:/opt/emqx/log
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - iot-bridge
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 800M

  rabbitmq:
    image: rabbitmq:4.2.6-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./services/rabbitmq/log:/var/log/rabbitmq
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - iot-bridge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M

  device-data-receiver:
    image: ghcr.io/warpstreamlabs/bento:1.17.0
    container_name: device-data-receiver
    ports:
      - "4195:4195"
    volumes:
      - ./services/device/data-receiver/pipeline.yaml:/bento.yaml
    env_file:
      - ./services/device/data-receiver/.env
    command:
      - -c
      - /bento.yaml
    restart: unless-stopped
    depends_on:
      - emqx
      - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - iot-bridge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 70M

  device-data-insert:
    image: ghcr.io/warpstreamlabs/bento:1.17.0
    container_name: device-data-insert
    ports:
      - "4196:4195"
    volumes:
      - ./services/device/data-insert/pipeline.yaml:/bento.yaml
    env_file:
      - ./services/device/data-insert/.env
    command:
      - -c
      - /bento.yaml
    restart: unless-stopped
    depends_on:
      - database
      - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - iot-bridge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 70M

  prometheus:
    image: prom/prometheus:v3.5.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - iot-bridge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  grafana:
    image: grafana/grafana:12.4.3
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      # - ./services/grafana/datasources/datasource.yml:/etc/grafana/provisioning/datasources/automatic.yml
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - iot-bridge
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
