-- Create "tenants" table
CREATE TABLE "tenants" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tenant_key" character varying NOT NULL,
  "name" character varying NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "status" character varying NOT NULL DEFAULT 'active',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "tenant_tenant_key" to table: "tenants"
CREATE UNIQUE INDEX "tenant_tenant_key" ON "tenants" ("tenant_key");
-- Create index "tenants_tenant_key_key" to table: "tenants"
CREATE UNIQUE INDEX "tenants_tenant_key_key" ON "tenants" ("tenant_key");
-- Create "model_categories" table
CREATE TABLE "model_categories" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "tenant_key" character varying NOT NULL,
  "category_key" character varying NOT NULL,
  "display_name" character varying NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "icon" character varying NOT NULL DEFAULT '',
  "sort_order" bigint NOT NULL DEFAULT 0,
  "status" character varying NOT NULL DEFAULT 'active',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "tenant_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "model_categories_tenants_model_categories" FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "modelcategory_tenant_key" to table: "model_categories"
CREATE INDEX "modelcategory_tenant_key" ON "model_categories" ("tenant_key");
-- Create index "modelcategory_tenant_key_category_key" to table: "model_categories"
CREATE UNIQUE INDEX "modelcategory_tenant_key_category_key" ON "model_categories" ("tenant_key", "category_key");
-- Create index "modelcategory_tenant_key_sort_order" to table: "model_categories"
CREATE INDEX "modelcategory_tenant_key_sort_order" ON "model_categories" ("tenant_key", "sort_order");
-- Create "thing_models" table
CREATE TABLE "thing_models" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "model_key" character varying NOT NULL,
  "tenant_key" character varying NOT NULL,
  "name" character varying NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "category" character varying NOT NULL,
  "properties" jsonb NOT NULL,
  "services" jsonb NOT NULL,
  "events" jsonb NOT NULL,
  "version" character varying NOT NULL DEFAULT '1.0',
  "status" character varying NOT NULL DEFAULT 'active',
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "model_category_id" bigint NOT NULL,
  "tenant_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "thing_models_model_categories_thing_models" FOREIGN KEY ("model_category_id") REFERENCES "model_categories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "thing_models_tenants_thing_models" FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "thing_models_model_key_key" to table: "thing_models"
CREATE UNIQUE INDEX "thing_models_model_key_key" ON "thing_models" ("model_key");
-- Create index "thingmodel_tenant_key" to table: "thing_models"
CREATE INDEX "thingmodel_tenant_key" ON "thing_models" ("tenant_key");
-- Create index "thingmodel_tenant_key_category" to table: "thing_models"
CREATE INDEX "thingmodel_tenant_key_category" ON "thing_models" ("tenant_key", "category");
-- Create "devices" table
CREATE TABLE "devices" (
  "dev_id" character varying NOT NULL,
  "tenant_key" character varying NOT NULL,
  "model_key" character varying NOT NULL,
  "device_name" character varying NOT NULL DEFAULT '',
  "access_key" character varying NOT NULL,
  "firmware_ver" character varying NOT NULL DEFAULT '',
  "properties_cfg" jsonb NOT NULL,
  "status" character varying NOT NULL DEFAULT 'active',
  "online" boolean NOT NULL DEFAULT false,
  "metadata" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "last_seen" timestamptz NULL,
  "tenant_id" bigint NOT NULL,
  "thing_model_id" bigint NOT NULL,
  PRIMARY KEY ("dev_id"),
  CONSTRAINT "devices_tenants_devices" FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "devices_thing_models_devices" FOREIGN KEY ("thing_model_id") REFERENCES "thing_models" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "device_status" to table: "devices"
CREATE INDEX "device_status" ON "devices" ("status");
-- Create index "device_tenant_key" to table: "devices"
CREATE INDEX "device_tenant_key" ON "devices" ("tenant_key");
-- Create index "device_tenant_key_model_key" to table: "devices"
CREATE INDEX "device_tenant_key_model_key" ON "devices" ("tenant_key", "model_key");
-- Create index "device_tenant_key_status" to table: "devices"
CREATE INDEX "device_tenant_key_status" ON "devices" ("tenant_key", "status");
-- Create index "devices_access_key_key" to table: "devices"
CREATE UNIQUE INDEX "devices_access_key_key" ON "devices" ("access_key");
-- Drop "device_telemetry" table
DROP TABLE "device_telemetry";
