// Code generated by ent, DO NOT EDIT.

package devicetelemetry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Seeker32/AssassinIoT/backend/ent/predicate"
)

// Time applies equality check predicate on the "time" field. It's identical to TimeEQ.
func Time(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldTime, v))
}

// DeviceIdentifier applies equality check predicate on the "device_identifier" field. It's identical to DeviceIdentifierEQ.
func DeviceIdentifier(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldDeviceIdentifier, v))
}

// PropertyName applies equality check predicate on the "property_name" field. It's identical to PropertyNameEQ.
func PropertyName(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldPropertyName, v))
}

// ValueInt applies equality check predicate on the "value_int" field. It's identical to ValueIntEQ.
func ValueInt(v int32) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldValueInt, v))
}

// ValueFloat applies equality check predicate on the "value_float" field. It's identical to ValueFloatEQ.
func ValueFloat(v float64) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldValueFloat, v))
}

// ValueString applies equality check predicate on the "value_string" field. It's identical to ValueStringEQ.
func ValueString(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldValueString, v))
}

// ValueBool applies equality check predicate on the "value_bool" field. It's identical to ValueBoolEQ.
func ValueBool(v bool) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldValueBool, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldReceivedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldCreatedAt, v))
}

// TimeEQ applies the EQ predicate on the "time" field.
func TimeEQ(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldTime, v))
}

// TimeNEQ applies the NEQ predicate on the "time" field.
func TimeNEQ(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNEQ(FieldTime, v))
}

// TimeIn applies the In predicate on the "time" field.
func TimeIn(vs ...time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIn(FieldTime, vs...))
}

// TimeNotIn applies the NotIn predicate on the "time" field.
func TimeNotIn(vs ...time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotIn(FieldTime, vs...))
}

// TimeGT applies the GT predicate on the "time" field.
func TimeGT(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGT(FieldTime, v))
}

// TimeGTE applies the GTE predicate on the "time" field.
func TimeGTE(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGTE(FieldTime, v))
}

// TimeLT applies the LT predicate on the "time" field.
func TimeLT(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLT(FieldTime, v))
}

// TimeLTE applies the LTE predicate on the "time" field.
func TimeLTE(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLTE(FieldTime, v))
}

// DeviceIdentifierEQ applies the EQ predicate on the "device_identifier" field.
func DeviceIdentifierEQ(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldDeviceIdentifier, v))
}

// DeviceIdentifierNEQ applies the NEQ predicate on the "device_identifier" field.
func DeviceIdentifierNEQ(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNEQ(FieldDeviceIdentifier, v))
}

// DeviceIdentifierIn applies the In predicate on the "device_identifier" field.
func DeviceIdentifierIn(vs ...string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIn(FieldDeviceIdentifier, vs...))
}

// DeviceIdentifierNotIn applies the NotIn predicate on the "device_identifier" field.
func DeviceIdentifierNotIn(vs ...string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotIn(FieldDeviceIdentifier, vs...))
}

// DeviceIdentifierGT applies the GT predicate on the "device_identifier" field.
func DeviceIdentifierGT(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGT(FieldDeviceIdentifier, v))
}

// DeviceIdentifierGTE applies the GTE predicate on the "device_identifier" field.
func DeviceIdentifierGTE(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGTE(FieldDeviceIdentifier, v))
}

// DeviceIdentifierLT applies the LT predicate on the "device_identifier" field.
func DeviceIdentifierLT(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLT(FieldDeviceIdentifier, v))
}

// DeviceIdentifierLTE applies the LTE predicate on the "device_identifier" field.
func DeviceIdentifierLTE(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLTE(FieldDeviceIdentifier, v))
}

// DeviceIdentifierContains applies the Contains predicate on the "device_identifier" field.
func DeviceIdentifierContains(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldContains(FieldDeviceIdentifier, v))
}

// DeviceIdentifierHasPrefix applies the HasPrefix predicate on the "device_identifier" field.
func DeviceIdentifierHasPrefix(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldHasPrefix(FieldDeviceIdentifier, v))
}

// DeviceIdentifierHasSuffix applies the HasSuffix predicate on the "device_identifier" field.
func DeviceIdentifierHasSuffix(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldHasSuffix(FieldDeviceIdentifier, v))
}

// DeviceIdentifierEqualFold applies the EqualFold predicate on the "device_identifier" field.
func DeviceIdentifierEqualFold(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEqualFold(FieldDeviceIdentifier, v))
}

// DeviceIdentifierContainsFold applies the ContainsFold predicate on the "device_identifier" field.
func DeviceIdentifierContainsFold(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldContainsFold(FieldDeviceIdentifier, v))
}

// PropertyNameEQ applies the EQ predicate on the "property_name" field.
func PropertyNameEQ(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldPropertyName, v))
}

// PropertyNameNEQ applies the NEQ predicate on the "property_name" field.
func PropertyNameNEQ(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNEQ(FieldPropertyName, v))
}

// PropertyNameIn applies the In predicate on the "property_name" field.
func PropertyNameIn(vs ...string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIn(FieldPropertyName, vs...))
}

// PropertyNameNotIn applies the NotIn predicate on the "property_name" field.
func PropertyNameNotIn(vs ...string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotIn(FieldPropertyName, vs...))
}

// PropertyNameGT applies the GT predicate on the "property_name" field.
func PropertyNameGT(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGT(FieldPropertyName, v))
}

// PropertyNameGTE applies the GTE predicate on the "property_name" field.
func PropertyNameGTE(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGTE(FieldPropertyName, v))
}

// PropertyNameLT applies the LT predicate on the "property_name" field.
func PropertyNameLT(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLT(FieldPropertyName, v))
}

// PropertyNameLTE applies the LTE predicate on the "property_name" field.
func PropertyNameLTE(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLTE(FieldPropertyName, v))
}

// PropertyNameContains applies the Contains predicate on the "property_name" field.
func PropertyNameContains(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldContains(FieldPropertyName, v))
}

// PropertyNameHasPrefix applies the HasPrefix predicate on the "property_name" field.
func PropertyNameHasPrefix(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldHasPrefix(FieldPropertyName, v))
}

// PropertyNameHasSuffix applies the HasSuffix predicate on the "property_name" field.
func PropertyNameHasSuffix(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldHasSuffix(FieldPropertyName, v))
}

// PropertyNameEqualFold applies the EqualFold predicate on the "property_name" field.
func PropertyNameEqualFold(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEqualFold(FieldPropertyName, v))
}

// PropertyNameContainsFold applies the ContainsFold predicate on the "property_name" field.
func PropertyNameContainsFold(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldContainsFold(FieldPropertyName, v))
}

// ValueTypeEQ applies the EQ predicate on the "value_type" field.
func ValueTypeEQ(v ValueType) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldValueType, v))
}

// ValueTypeNEQ applies the NEQ predicate on the "value_type" field.
func ValueTypeNEQ(v ValueType) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNEQ(FieldValueType, v))
}

// ValueTypeIn applies the In predicate on the "value_type" field.
func ValueTypeIn(vs ...ValueType) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIn(FieldValueType, vs...))
}

// ValueTypeNotIn applies the NotIn predicate on the "value_type" field.
func ValueTypeNotIn(vs ...ValueType) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotIn(FieldValueType, vs...))
}

// ValueIntEQ applies the EQ predicate on the "value_int" field.
func ValueIntEQ(v int32) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldValueInt, v))
}

// ValueIntNEQ applies the NEQ predicate on the "value_int" field.
func ValueIntNEQ(v int32) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNEQ(FieldValueInt, v))
}

// ValueIntIn applies the In predicate on the "value_int" field.
func ValueIntIn(vs ...int32) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIn(FieldValueInt, vs...))
}

// ValueIntNotIn applies the NotIn predicate on the "value_int" field.
func ValueIntNotIn(vs ...int32) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotIn(FieldValueInt, vs...))
}

// ValueIntGT applies the GT predicate on the "value_int" field.
func ValueIntGT(v int32) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGT(FieldValueInt, v))
}

// ValueIntGTE applies the GTE predicate on the "value_int" field.
func ValueIntGTE(v int32) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGTE(FieldValueInt, v))
}

// ValueIntLT applies the LT predicate on the "value_int" field.
func ValueIntLT(v int32) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLT(FieldValueInt, v))
}

// ValueIntLTE applies the LTE predicate on the "value_int" field.
func ValueIntLTE(v int32) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLTE(FieldValueInt, v))
}

// ValueIntIsNil applies the IsNil predicate on the "value_int" field.
func ValueIntIsNil() predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIsNull(FieldValueInt))
}

// ValueIntNotNil applies the NotNil predicate on the "value_int" field.
func ValueIntNotNil() predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotNull(FieldValueInt))
}

// ValueFloatEQ applies the EQ predicate on the "value_float" field.
func ValueFloatEQ(v float64) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldValueFloat, v))
}

// ValueFloatNEQ applies the NEQ predicate on the "value_float" field.
func ValueFloatNEQ(v float64) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNEQ(FieldValueFloat, v))
}

// ValueFloatIn applies the In predicate on the "value_float" field.
func ValueFloatIn(vs ...float64) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIn(FieldValueFloat, vs...))
}

// ValueFloatNotIn applies the NotIn predicate on the "value_float" field.
func ValueFloatNotIn(vs ...float64) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotIn(FieldValueFloat, vs...))
}

// ValueFloatGT applies the GT predicate on the "value_float" field.
func ValueFloatGT(v float64) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGT(FieldValueFloat, v))
}

// ValueFloatGTE applies the GTE predicate on the "value_float" field.
func ValueFloatGTE(v float64) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGTE(FieldValueFloat, v))
}

// ValueFloatLT applies the LT predicate on the "value_float" field.
func ValueFloatLT(v float64) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLT(FieldValueFloat, v))
}

// ValueFloatLTE applies the LTE predicate on the "value_float" field.
func ValueFloatLTE(v float64) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLTE(FieldValueFloat, v))
}

// ValueFloatIsNil applies the IsNil predicate on the "value_float" field.
func ValueFloatIsNil() predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIsNull(FieldValueFloat))
}

// ValueFloatNotNil applies the NotNil predicate on the "value_float" field.
func ValueFloatNotNil() predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotNull(FieldValueFloat))
}

// ValueStringEQ applies the EQ predicate on the "value_string" field.
func ValueStringEQ(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldValueString, v))
}

// ValueStringNEQ applies the NEQ predicate on the "value_string" field.
func ValueStringNEQ(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNEQ(FieldValueString, v))
}

// ValueStringIn applies the In predicate on the "value_string" field.
func ValueStringIn(vs ...string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIn(FieldValueString, vs...))
}

// ValueStringNotIn applies the NotIn predicate on the "value_string" field.
func ValueStringNotIn(vs ...string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotIn(FieldValueString, vs...))
}

// ValueStringGT applies the GT predicate on the "value_string" field.
func ValueStringGT(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGT(FieldValueString, v))
}

// ValueStringGTE applies the GTE predicate on the "value_string" field.
func ValueStringGTE(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGTE(FieldValueString, v))
}

// ValueStringLT applies the LT predicate on the "value_string" field.
func ValueStringLT(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLT(FieldValueString, v))
}

// ValueStringLTE applies the LTE predicate on the "value_string" field.
func ValueStringLTE(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLTE(FieldValueString, v))
}

// ValueStringContains applies the Contains predicate on the "value_string" field.
func ValueStringContains(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldContains(FieldValueString, v))
}

// ValueStringHasPrefix applies the HasPrefix predicate on the "value_string" field.
func ValueStringHasPrefix(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldHasPrefix(FieldValueString, v))
}

// ValueStringHasSuffix applies the HasSuffix predicate on the "value_string" field.
func ValueStringHasSuffix(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldHasSuffix(FieldValueString, v))
}

// ValueStringIsNil applies the IsNil predicate on the "value_string" field.
func ValueStringIsNil() predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIsNull(FieldValueString))
}

// ValueStringNotNil applies the NotNil predicate on the "value_string" field.
func ValueStringNotNil() predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotNull(FieldValueString))
}

// ValueStringEqualFold applies the EqualFold predicate on the "value_string" field.
func ValueStringEqualFold(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEqualFold(FieldValueString, v))
}

// ValueStringContainsFold applies the ContainsFold predicate on the "value_string" field.
func ValueStringContainsFold(v string) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldContainsFold(FieldValueString, v))
}

// ValueBoolEQ applies the EQ predicate on the "value_bool" field.
func ValueBoolEQ(v bool) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldValueBool, v))
}

// ValueBoolNEQ applies the NEQ predicate on the "value_bool" field.
func ValueBoolNEQ(v bool) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNEQ(FieldValueBool, v))
}

// ValueBoolIsNil applies the IsNil predicate on the "value_bool" field.
func ValueBoolIsNil() predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIsNull(FieldValueBool))
}

// ValueBoolNotNil applies the NotNil predicate on the "value_bool" field.
func ValueBoolNotNil() predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotNull(FieldValueBool))
}

// ValueJSONIsNil applies the IsNil predicate on the "value_json" field.
func ValueJSONIsNil() predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIsNull(FieldValueJSON))
}

// ValueJSONNotNil applies the NotNil predicate on the "value_json" field.
func ValueJSONNotNil() predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotNull(FieldValueJSON))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLTE(FieldReceivedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeviceTelemetry) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeviceTelemetry) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeviceTelemetry) predicate.DeviceTelemetry {
	return predicate.DeviceTelemetry(sql.NotPredicates(p))
}
