// Code generated by ent, DO NOT EDIT.

package thingmodel

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the thingmodel type in the database.
	Label = "thing_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldModelKey holds the string denoting the model_key field in the database.
	FieldModelKey = "model_key"
	// FieldTenantKey holds the string denoting the tenant_key field in the database.
	FieldTenantKey = "tenant_key"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldProperties holds the string denoting the properties field in the database.
	FieldProperties = "properties"
	// FieldServices holds the string denoting the services field in the database.
	FieldServices = "services"
	// FieldEvents holds the string denoting the events field in the database.
	FieldEvents = "events"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldModelCategoryID holds the string denoting the model_category_id field in the database.
	FieldModelCategoryID = "model_category_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeModelCategory holds the string denoting the model_category edge name in mutations.
	EdgeModelCategory = "model_category"
	// EdgeDevices holds the string denoting the devices edge name in mutations.
	EdgeDevices = "devices"
	// Table holds the table name of the thingmodel in the database.
	Table = "thing_models"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "thing_models"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// ModelCategoryTable is the table that holds the model_category relation/edge.
	ModelCategoryTable = "thing_models"
	// ModelCategoryInverseTable is the table name for the ModelCategory entity.
	// It exists in this package in order to avoid circular dependency with the "modelcategory" package.
	ModelCategoryInverseTable = "model_categories"
	// ModelCategoryColumn is the table column denoting the model_category relation/edge.
	ModelCategoryColumn = "model_category_id"
	// DevicesTable is the table that holds the devices relation/edge.
	DevicesTable = "devices"
	// DevicesInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DevicesInverseTable = "devices"
	// DevicesColumn is the table column denoting the devices relation/edge.
	DevicesColumn = "thing_model_id"
)

// Columns holds all SQL columns for thingmodel fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldModelKey,
	FieldTenantKey,
	FieldName,
	FieldDescription,
	FieldCategory,
	FieldProperties,
	FieldServices,
	FieldEvents,
	FieldVersion,
	FieldTenantID,
	FieldModelCategoryID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelKeyValidator is a validator for the "model_key" field. It is called by the builders before save.
	ModelKeyValidator func(string) error
	// TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	TenantKeyValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultProperties holds the default value on creation for the "properties" field.
	DefaultProperties map[string]interface{}
	// DefaultServices holds the default value on creation for the "services" field.
	DefaultServices map[string]interface{}
	// DefaultEvents holds the default value on creation for the "events" field.
	DefaultEvents map[string]interface{}
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion string
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive     Status = "active"
	StatusDeprecated Status = "deprecated"
	StatusDisabled   Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDeprecated, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("thingmodel: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ThingModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByModelKey orders the results by the model_key field.
func ByModelKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelKey, opts...).ToFunc()
}

// ByTenantKey orders the results by the tenant_key field.
func ByTenantKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantKey, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByModelCategoryID orders the results by the model_category_id field.
func ByModelCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelCategoryID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByModelCategoryField orders the results by model_category field.
func ByModelCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByDevicesCount orders the results by devices count.
func ByDevicesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDevicesStep(), opts...)
	}
}

// ByDevices orders the results by devices terms.
func ByDevices(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDevicesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newModelCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelCategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModelCategoryTable, ModelCategoryColumn),
	)
}
func newDevicesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DevicesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DevicesTable, DevicesColumn),
	)
}
