// Code generated by ent, DO NOT EDIT.

package thingmodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Seeker32/AssassinIoT/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLTE(FieldID, id))
}

// ModelKey applies equality check predicate on the "model_key" field. It's identical to ModelKeyEQ.
func ModelKey(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldModelKey, v))
}

// TenantKey applies equality check predicate on the "tenant_key" field. It's identical to TenantKeyEQ.
func TenantKey(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldTenantKey, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldDescription, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldCategory, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldVersion, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldTenantID, v))
}

// ModelCategoryID applies equality check predicate on the "model_category_id" field. It's identical to ModelCategoryIDEQ.
func ModelCategoryID(v int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldModelCategoryID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelKeyEQ applies the EQ predicate on the "model_key" field.
func ModelKeyEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldModelKey, v))
}

// ModelKeyNEQ applies the NEQ predicate on the "model_key" field.
func ModelKeyNEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldModelKey, v))
}

// ModelKeyIn applies the In predicate on the "model_key" field.
func ModelKeyIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldModelKey, vs...))
}

// ModelKeyNotIn applies the NotIn predicate on the "model_key" field.
func ModelKeyNotIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldModelKey, vs...))
}

// ModelKeyGT applies the GT predicate on the "model_key" field.
func ModelKeyGT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGT(FieldModelKey, v))
}

// ModelKeyGTE applies the GTE predicate on the "model_key" field.
func ModelKeyGTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGTE(FieldModelKey, v))
}

// ModelKeyLT applies the LT predicate on the "model_key" field.
func ModelKeyLT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLT(FieldModelKey, v))
}

// ModelKeyLTE applies the LTE predicate on the "model_key" field.
func ModelKeyLTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLTE(FieldModelKey, v))
}

// ModelKeyContains applies the Contains predicate on the "model_key" field.
func ModelKeyContains(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContains(FieldModelKey, v))
}

// ModelKeyHasPrefix applies the HasPrefix predicate on the "model_key" field.
func ModelKeyHasPrefix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasPrefix(FieldModelKey, v))
}

// ModelKeyHasSuffix applies the HasSuffix predicate on the "model_key" field.
func ModelKeyHasSuffix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasSuffix(FieldModelKey, v))
}

// ModelKeyEqualFold applies the EqualFold predicate on the "model_key" field.
func ModelKeyEqualFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEqualFold(FieldModelKey, v))
}

// ModelKeyContainsFold applies the ContainsFold predicate on the "model_key" field.
func ModelKeyContainsFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContainsFold(FieldModelKey, v))
}

// TenantKeyEQ applies the EQ predicate on the "tenant_key" field.
func TenantKeyEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldTenantKey, v))
}

// TenantKeyNEQ applies the NEQ predicate on the "tenant_key" field.
func TenantKeyNEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldTenantKey, v))
}

// TenantKeyIn applies the In predicate on the "tenant_key" field.
func TenantKeyIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldTenantKey, vs...))
}

// TenantKeyNotIn applies the NotIn predicate on the "tenant_key" field.
func TenantKeyNotIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldTenantKey, vs...))
}

// TenantKeyGT applies the GT predicate on the "tenant_key" field.
func TenantKeyGT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGT(FieldTenantKey, v))
}

// TenantKeyGTE applies the GTE predicate on the "tenant_key" field.
func TenantKeyGTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGTE(FieldTenantKey, v))
}

// TenantKeyLT applies the LT predicate on the "tenant_key" field.
func TenantKeyLT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLT(FieldTenantKey, v))
}

// TenantKeyLTE applies the LTE predicate on the "tenant_key" field.
func TenantKeyLTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLTE(FieldTenantKey, v))
}

// TenantKeyContains applies the Contains predicate on the "tenant_key" field.
func TenantKeyContains(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContains(FieldTenantKey, v))
}

// TenantKeyHasPrefix applies the HasPrefix predicate on the "tenant_key" field.
func TenantKeyHasPrefix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasPrefix(FieldTenantKey, v))
}

// TenantKeyHasSuffix applies the HasSuffix predicate on the "tenant_key" field.
func TenantKeyHasSuffix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasSuffix(FieldTenantKey, v))
}

// TenantKeyEqualFold applies the EqualFold predicate on the "tenant_key" field.
func TenantKeyEqualFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEqualFold(FieldTenantKey, v))
}

// TenantKeyContainsFold applies the ContainsFold predicate on the "tenant_key" field.
func TenantKeyContainsFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContainsFold(FieldTenantKey, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContainsFold(FieldDescription, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContainsFold(FieldCategory, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldContainsFold(FieldVersion, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldTenantID, vs...))
}

// ModelCategoryIDEQ applies the EQ predicate on the "model_category_id" field.
func ModelCategoryIDEQ(v int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldModelCategoryID, v))
}

// ModelCategoryIDNEQ applies the NEQ predicate on the "model_category_id" field.
func ModelCategoryIDNEQ(v int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldModelCategoryID, v))
}

// ModelCategoryIDIn applies the In predicate on the "model_category_id" field.
func ModelCategoryIDIn(vs ...int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldModelCategoryID, vs...))
}

// ModelCategoryIDNotIn applies the NotIn predicate on the "model_category_id" field.
func ModelCategoryIDNotIn(vs ...int) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldModelCategoryID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ThingModel {
	return predicate.ThingModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.ThingModel {
	return predicate.ThingModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.ThingModel {
	return predicate.ThingModel(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasModelCategory applies the HasEdge predicate on the "model_category" edge.
func HasModelCategory() predicate.ThingModel {
	return predicate.ThingModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ModelCategoryTable, ModelCategoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelCategoryWith applies the HasEdge predicate on the "model_category" edge with a given conditions (other predicates).
func HasModelCategoryWith(preds ...predicate.ModelCategory) predicate.ThingModel {
	return predicate.ThingModel(func(s *sql.Selector) {
		step := newModelCategoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDevices applies the HasEdge predicate on the "devices" edge.
func HasDevices() predicate.ThingModel {
	return predicate.ThingModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DevicesTable, DevicesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDevicesWith applies the HasEdge predicate on the "devices" edge with a given conditions (other predicates).
func HasDevicesWith(preds ...predicate.Device) predicate.ThingModel {
	return predicate.ThingModel(func(s *sql.Selector) {
		step := newDevicesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ThingModel) predicate.ThingModel {
	return predicate.ThingModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ThingModel) predicate.ThingModel {
	return predicate.ThingModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ThingModel) predicate.ThingModel {
	return predicate.ThingModel(sql.NotPredicates(p))
}
