// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Seeker32/AssassinIoT/ent/devicetelemetry"
)

// DeviceTelemetry is the model entity for the DeviceTelemetry schema.
type DeviceTelemetry struct {
	config `json:"-"`
	// Time holds the value of the "time" field.
	Time time.Time `json:"time,omitempty"`
	// DeviceIdentifier holds the value of the "device_identifier" field.
	DeviceIdentifier string `json:"device_identifier,omitempty"`
	// PropertyName holds the value of the "property_name" field.
	PropertyName string `json:"property_name,omitempty"`
	// ValueType holds the value of the "value_type" field.
	ValueType devicetelemetry.ValueType `json:"value_type,omitempty"`
	// ValueInt holds the value of the "value_int" field.
	ValueInt *int32 `json:"value_int,omitempty"`
	// ValueFloat holds the value of the "value_float" field.
	ValueFloat *float64 `json:"value_float,omitempty"`
	// ValueString holds the value of the "value_string" field.
	ValueString *string `json:"value_string,omitempty"`
	// ValueBool holds the value of the "value_bool" field.
	ValueBool *bool `json:"value_bool,omitempty"`
	// ValueJSON holds the value of the "value_json" field.
	ValueJSON map[string]interface{} `json:"value_json,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt time.Time `json:"received_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeviceTelemetry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case devicetelemetry.FieldValueJSON:
			values[i] = new([]byte)
		case devicetelemetry.FieldValueBool:
			values[i] = new(sql.NullBool)
		case devicetelemetry.FieldValueFloat:
			values[i] = new(sql.NullFloat64)
		case devicetelemetry.FieldValueInt:
			values[i] = new(sql.NullInt64)
		case devicetelemetry.FieldDeviceIdentifier, devicetelemetry.FieldPropertyName, devicetelemetry.FieldValueType, devicetelemetry.FieldValueString:
			values[i] = new(sql.NullString)
		case devicetelemetry.FieldTime, devicetelemetry.FieldReceivedAt, devicetelemetry.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeviceTelemetry fields.
func (_m *DeviceTelemetry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case devicetelemetry.FieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				_m.Time = value.Time
			}
		case devicetelemetry.FieldDeviceIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_identifier", values[i])
			} else if value.Valid {
				_m.DeviceIdentifier = value.String
			}
		case devicetelemetry.FieldPropertyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field property_name", values[i])
			} else if value.Valid {
				_m.PropertyName = value.String
			}
		case devicetelemetry.FieldValueType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value_type", values[i])
			} else if value.Valid {
				_m.ValueType = devicetelemetry.ValueType(value.String)
			}
		case devicetelemetry.FieldValueInt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field value_int", values[i])
			} else if value.Valid {
				_m.ValueInt = new(int32)
				*_m.ValueInt = int32(value.Int64)
			}
		case devicetelemetry.FieldValueFloat:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field value_float", values[i])
			} else if value.Valid {
				_m.ValueFloat = new(float64)
				*_m.ValueFloat = value.Float64
			}
		case devicetelemetry.FieldValueString:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value_string", values[i])
			} else if value.Valid {
				_m.ValueString = new(string)
				*_m.ValueString = value.String
			}
		case devicetelemetry.FieldValueBool:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field value_bool", values[i])
			} else if value.Valid {
				_m.ValueBool = new(bool)
				*_m.ValueBool = value.Bool
			}
		case devicetelemetry.FieldValueJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field value_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ValueJSON); err != nil {
					return fmt.Errorf("unmarshal field value_json: %w", err)
				}
			}
		case devicetelemetry.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		case devicetelemetry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeviceTelemetry.
// This includes values selected through modifiers, order, etc.
func (_m *DeviceTelemetry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Unwrap unwraps the DeviceTelemetry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DeviceTelemetry) Unwrap() *DeviceTelemetry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeviceTelemetry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DeviceTelemetry) String() string {
	var builder strings.Builder
	builder.WriteString("DeviceTelemetry(")
	builder.WriteString("time=")
	builder.WriteString(_m.Time.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("device_identifier=")
	builder.WriteString(_m.DeviceIdentifier)
	builder.WriteString(", ")
	builder.WriteString("property_name=")
	builder.WriteString(_m.PropertyName)
	builder.WriteString(", ")
	builder.WriteString("value_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValueType))
	builder.WriteString(", ")
	if v := _m.ValueInt; v != nil {
		builder.WriteString("value_int=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ValueFloat; v != nil {
		builder.WriteString("value_float=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ValueString; v != nil {
		builder.WriteString("value_string=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ValueBool; v != nil {
		builder.WriteString("value_bool=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("value_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValueJSON))
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeviceTelemetries is a parsable slice of DeviceTelemetry.
type DeviceTelemetries []*DeviceTelemetry
