// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Seeker32/AssassinIoT/backend/ent/device"
	"github.com/Seeker32/AssassinIoT/backend/ent/tenant"
	"github.com/Seeker32/AssassinIoT/backend/ent/thingmodel"
)

// Device is the model entity for the Device schema.
type Device struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 软删除时间，非空表示已删除
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 所属租户
	TenantKey string `json:"tenant_key,omitempty"`
	// 绑定的物模型
	ModelKey string `json:"model_key,omitempty"`
	// 设备名称
	DeviceName string `json:"device_name,omitempty"`
	// 设备接入密钥，用于 MQTT 认证
	AccessKey string `json:"access_key,omitempty"`
	// 当前固件版本
	FirmwareVer string `json:"firmware_ver,omitempty"`
	// 属性个性化配置，可覆盖物模型中属性的默认值
	PropertiesCfg map[string]interface{} `json:"properties_cfg,omitempty"`
	// 租户 ID 外键
	TenantID int `json:"tenant_id,omitempty"`
	// 物模型 ID 外键
	ThingModelID int `json:"thing_model_id,omitempty"`
	// 设备状态：active=正常, inactive=未激活, disabled=已禁用
	Status device.Status `json:"status,omitempty"`
	// 是否在线（运行时更新）
	Online bool `json:"online,omitempty"`
	// 扩展元数据，如安装位置、厂商信息等
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 最后在线时间
	LastSeen *time.Time `json:"last_seen,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceQuery when eager-loading is set.
	Edges        DeviceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeviceEdges holds the relations/edges for other nodes in the graph.
type DeviceEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// ThingModel holds the value of the thing_model edge.
	ThingModel *ThingModel `json:"thing_model,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// ThingModelOrErr returns the ThingModel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceEdges) ThingModelOrErr() (*ThingModel, error) {
	if e.ThingModel != nil {
		return e.ThingModel, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: thingmodel.Label}
	}
	return nil, &NotLoadedError{edge: "thing_model"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Device) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case device.FieldPropertiesCfg, device.FieldMetadata:
			values[i] = new([]byte)
		case device.FieldOnline:
			values[i] = new(sql.NullBool)
		case device.FieldID, device.FieldTenantID, device.FieldThingModelID:
			values[i] = new(sql.NullInt64)
		case device.FieldTenantKey, device.FieldModelKey, device.FieldDeviceName, device.FieldAccessKey, device.FieldFirmwareVer, device.FieldStatus:
			values[i] = new(sql.NullString)
		case device.FieldDeletedAt, device.FieldCreatedAt, device.FieldUpdatedAt, device.FieldLastSeen:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Device fields.
func (_m *Device) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case device.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case device.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case device.FieldTenantKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_key", values[i])
			} else if value.Valid {
				_m.TenantKey = value.String
			}
		case device.FieldModelKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_key", values[i])
			} else if value.Valid {
				_m.ModelKey = value.String
			}
		case device.FieldDeviceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_name", values[i])
			} else if value.Valid {
				_m.DeviceName = value.String
			}
		case device.FieldAccessKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_key", values[i])
			} else if value.Valid {
				_m.AccessKey = value.String
			}
		case device.FieldFirmwareVer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field firmware_ver", values[i])
			} else if value.Valid {
				_m.FirmwareVer = value.String
			}
		case device.FieldPropertiesCfg:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field properties_cfg", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PropertiesCfg); err != nil {
					return fmt.Errorf("unmarshal field properties_cfg: %w", err)
				}
			}
		case device.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case device.FieldThingModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field thing_model_id", values[i])
			} else if value.Valid {
				_m.ThingModelID = int(value.Int64)
			}
		case device.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = device.Status(value.String)
			}
		case device.FieldOnline:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field online", values[i])
			} else if value.Valid {
				_m.Online = value.Bool
			}
		case device.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case device.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case device.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case device.FieldLastSeen:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen", values[i])
			} else if value.Valid {
				_m.LastSeen = new(time.Time)
				*_m.LastSeen = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Device.
// This includes values selected through modifiers, order, etc.
func (_m *Device) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the Device entity.
func (_m *Device) QueryTenant() *TenantQuery {
	return NewDeviceClient(_m.config).QueryTenant(_m)
}

// QueryThingModel queries the "thing_model" edge of the Device entity.
func (_m *Device) QueryThingModel() *ThingModelQuery {
	return NewDeviceClient(_m.config).QueryThingModel(_m)
}

// Update returns a builder for updating this Device.
// Note that you need to call Device.Unwrap() before calling this method if this Device
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Device) Update() *DeviceUpdateOne {
	return NewDeviceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Device entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Device) Unwrap() *Device {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Device is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Device) String() string {
	var builder strings.Builder
	builder.WriteString("Device(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("tenant_key=")
	builder.WriteString(_m.TenantKey)
	builder.WriteString(", ")
	builder.WriteString("model_key=")
	builder.WriteString(_m.ModelKey)
	builder.WriteString(", ")
	builder.WriteString("device_name=")
	builder.WriteString(_m.DeviceName)
	builder.WriteString(", ")
	builder.WriteString("access_key=")
	builder.WriteString(_m.AccessKey)
	builder.WriteString(", ")
	builder.WriteString("firmware_ver=")
	builder.WriteString(_m.FirmwareVer)
	builder.WriteString(", ")
	builder.WriteString("properties_cfg=")
	builder.WriteString(fmt.Sprintf("%v", _m.PropertiesCfg))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("thing_model_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThingModelID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("online=")
	builder.WriteString(fmt.Sprintf("%v", _m.Online))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastSeen; v != nil {
		builder.WriteString("last_seen=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Devices is a parsable slice of Device.
type Devices []*Device
