// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Seeker32/AssassinIoT/ent/device"
	"github.com/Seeker32/AssassinIoT/ent/tenant"
	"github.com/Seeker32/AssassinIoT/ent/thingmodel"
)

// DeviceCreate is the builder for creating a Device entity.
type DeviceCreate struct {
	config
	mutation *DeviceMutation
	hooks    []Hook
}

// SetTenantKey sets the "tenant_key" field.
func (_c *DeviceCreate) SetTenantKey(v string) *DeviceCreate {
	_c.mutation.SetTenantKey(v)
	return _c
}

// SetModelKey sets the "model_key" field.
func (_c *DeviceCreate) SetModelKey(v string) *DeviceCreate {
	_c.mutation.SetModelKey(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *DeviceCreate) SetDeviceName(v string) *DeviceCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableDeviceName(v *string) *DeviceCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetAccessKey sets the "access_key" field.
func (_c *DeviceCreate) SetAccessKey(v string) *DeviceCreate {
	_c.mutation.SetAccessKey(v)
	return _c
}

// SetFirmwareVer sets the "firmware_ver" field.
func (_c *DeviceCreate) SetFirmwareVer(v string) *DeviceCreate {
	_c.mutation.SetFirmwareVer(v)
	return _c
}

// SetNillableFirmwareVer sets the "firmware_ver" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableFirmwareVer(v *string) *DeviceCreate {
	if v != nil {
		_c.SetFirmwareVer(*v)
	}
	return _c
}

// SetPropertiesCfg sets the "properties_cfg" field.
func (_c *DeviceCreate) SetPropertiesCfg(v map[string]interface{}) *DeviceCreate {
	_c.mutation.SetPropertiesCfg(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *DeviceCreate) SetTenantID(v int) *DeviceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetThingModelID sets the "thing_model_id" field.
func (_c *DeviceCreate) SetThingModelID(v int) *DeviceCreate {
	_c.mutation.SetThingModelID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DeviceCreate) SetStatus(v device.Status) *DeviceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableStatus(v *device.Status) *DeviceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetOnline sets the "online" field.
func (_c *DeviceCreate) SetOnline(v bool) *DeviceCreate {
	_c.mutation.SetOnline(v)
	return _c
}

// SetNillableOnline sets the "online" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableOnline(v *bool) *DeviceCreate {
	if v != nil {
		_c.SetOnline(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *DeviceCreate) SetMetadata(v map[string]interface{}) *DeviceCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeviceCreate) SetCreatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableCreatedAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeviceCreate) SetUpdatedAt(v time.Time) *DeviceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableUpdatedAt(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *DeviceCreate) SetLastSeen(v time.Time) *DeviceCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_c *DeviceCreate) SetNillableLastSeen(v *time.Time) *DeviceCreate {
	if v != nil {
		_c.SetLastSeen(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DeviceCreate) SetID(v string) *DeviceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *DeviceCreate) SetTenant(v *Tenant) *DeviceCreate {
	return _c.SetTenantID(v.ID)
}

// SetThingModel sets the "thing_model" edge to the ThingModel entity.
func (_c *DeviceCreate) SetThingModel(v *ThingModel) *DeviceCreate {
	return _c.SetThingModelID(v.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (_c *DeviceCreate) Mutation() *DeviceMutation {
	return _c.mutation
}

// Save creates the Device in the database.
func (_c *DeviceCreate) Save(ctx context.Context) (*Device, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeviceCreate) SaveX(ctx context.Context) *Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeviceCreate) defaults() {
	if _, ok := _c.mutation.DeviceName(); !ok {
		v := device.DefaultDeviceName
		_c.mutation.SetDeviceName(v)
	}
	if _, ok := _c.mutation.FirmwareVer(); !ok {
		v := device.DefaultFirmwareVer
		_c.mutation.SetFirmwareVer(v)
	}
	if _, ok := _c.mutation.PropertiesCfg(); !ok {
		v := device.DefaultPropertiesCfg
		_c.mutation.SetPropertiesCfg(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := device.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Online(); !ok {
		v := device.DefaultOnline
		_c.mutation.SetOnline(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := device.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := device.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := device.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeviceCreate) check() error {
	if _, ok := _c.mutation.TenantKey(); !ok {
		return &ValidationError{Name: "tenant_key", err: errors.New(`ent: missing required field "Device.tenant_key"`)}
	}
	if v, ok := _c.mutation.TenantKey(); ok {
		if err := device.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`ent: validator failed for field "Device.tenant_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelKey(); !ok {
		return &ValidationError{Name: "model_key", err: errors.New(`ent: missing required field "Device.model_key"`)}
	}
	if v, ok := _c.mutation.ModelKey(); ok {
		if err := device.ModelKeyValidator(v); err != nil {
			return &ValidationError{Name: "model_key", err: fmt.Errorf(`ent: validator failed for field "Device.model_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		return &ValidationError{Name: "device_name", err: errors.New(`ent: missing required field "Device.device_name"`)}
	}
	if v, ok := _c.mutation.DeviceName(); ok {
		if err := device.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "Device.device_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccessKey(); !ok {
		return &ValidationError{Name: "access_key", err: errors.New(`ent: missing required field "Device.access_key"`)}
	}
	if v, ok := _c.mutation.AccessKey(); ok {
		if err := device.AccessKeyValidator(v); err != nil {
			return &ValidationError{Name: "access_key", err: fmt.Errorf(`ent: validator failed for field "Device.access_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FirmwareVer(); !ok {
		return &ValidationError{Name: "firmware_ver", err: errors.New(`ent: missing required field "Device.firmware_ver"`)}
	}
	if v, ok := _c.mutation.FirmwareVer(); ok {
		if err := device.FirmwareVerValidator(v); err != nil {
			return &ValidationError{Name: "firmware_ver", err: fmt.Errorf(`ent: validator failed for field "Device.firmware_ver": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PropertiesCfg(); !ok {
		return &ValidationError{Name: "properties_cfg", err: errors.New(`ent: missing required field "Device.properties_cfg"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Device.tenant_id"`)}
	}
	if _, ok := _c.mutation.ThingModelID(); !ok {
		return &ValidationError{Name: "thing_model_id", err: errors.New(`ent: missing required field "Device.thing_model_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Device.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := device.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Device.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Online(); !ok {
		return &ValidationError{Name: "online", err: errors.New(`ent: missing required field "Device.online"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "Device.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Device.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Device.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := device.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Device.id": %w`, err)}
		}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Device.tenant"`)}
	}
	if len(_c.mutation.ThingModelIDs()) == 0 {
		return &ValidationError{Name: "thing_model", err: errors.New(`ent: missing required edge "Device.thing_model"`)}
	}
	return nil
}

func (_c *DeviceCreate) sqlSave(ctx context.Context) (*Device, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Device.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeviceCreate) createSpec() (*Device, *sqlgraph.CreateSpec) {
	var (
		_node = &Device{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(device.Table, sqlgraph.NewFieldSpec(device.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantKey(); ok {
		_spec.SetField(device.FieldTenantKey, field.TypeString, value)
		_node.TenantKey = value
	}
	if value, ok := _c.mutation.ModelKey(); ok {
		_spec.SetField(device.FieldModelKey, field.TypeString, value)
		_node.ModelKey = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.AccessKey(); ok {
		_spec.SetField(device.FieldAccessKey, field.TypeString, value)
		_node.AccessKey = value
	}
	if value, ok := _c.mutation.FirmwareVer(); ok {
		_spec.SetField(device.FieldFirmwareVer, field.TypeString, value)
		_node.FirmwareVer = value
	}
	if value, ok := _c.mutation.PropertiesCfg(); ok {
		_spec.SetField(device.FieldPropertiesCfg, field.TypeJSON, value)
		_node.PropertiesCfg = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Online(); ok {
		_spec.SetField(device.FieldOnline, field.TypeBool, value)
		_node.Online = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(device.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(device.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(device.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = &value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.TenantTable,
			Columns: []string{device.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ThingModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.ThingModelTable,
			Columns: []string{device.ThingModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ThingModelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeviceCreateBulk is the builder for creating many Device entities in bulk.
type DeviceCreateBulk struct {
	config
	err      error
	builders []*DeviceCreate
}

// Save creates the Device entities in the database.
func (_c *DeviceCreateBulk) Save(ctx context.Context) ([]*Device, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Device, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeviceCreateBulk) SaveX(ctx context.Context) []*Device {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeviceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeviceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
