// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Seeker32/AssassinIoT/backend/ent/device"
	"github.com/Seeker32/AssassinIoT/backend/ent/predicate"
	"github.com/Seeker32/AssassinIoT/backend/ent/tenant"
	"github.com/Seeker32/AssassinIoT/backend/ent/thingmodel"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantKey sets the "tenant_key" field.
func (_u *DeviceUpdate) SetTenantKey(v string) *DeviceUpdate {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableTenantKey(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetModelKey sets the "model_key" field.
func (_u *DeviceUpdate) SetModelKey(v string) *DeviceUpdate {
	_u.mutation.SetModelKey(v)
	return _u
}

// SetNillableModelKey sets the "model_key" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableModelKey(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetModelKey(*v)
	}
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *DeviceUpdate) SetDeviceName(v string) *DeviceUpdate {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDeviceName(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetAccessKey sets the "access_key" field.
func (_u *DeviceUpdate) SetAccessKey(v string) *DeviceUpdate {
	_u.mutation.SetAccessKey(v)
	return _u
}

// SetNillableAccessKey sets the "access_key" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableAccessKey(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetAccessKey(*v)
	}
	return _u
}

// SetFirmwareVer sets the "firmware_ver" field.
func (_u *DeviceUpdate) SetFirmwareVer(v string) *DeviceUpdate {
	_u.mutation.SetFirmwareVer(v)
	return _u
}

// SetNillableFirmwareVer sets the "firmware_ver" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableFirmwareVer(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetFirmwareVer(*v)
	}
	return _u
}

// SetPropertiesCfg sets the "properties_cfg" field.
func (_u *DeviceUpdate) SetPropertiesCfg(v map[string]interface{}) *DeviceUpdate {
	_u.mutation.SetPropertiesCfg(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *DeviceUpdate) SetTenantID(v int) *DeviceUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableTenantID(v *int) *DeviceUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetThingModelID sets the "thing_model_id" field.
func (_u *DeviceUpdate) SetThingModelID(v int) *DeviceUpdate {
	_u.mutation.SetThingModelID(v)
	return _u
}

// SetNillableThingModelID sets the "thing_model_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableThingModelID(v *int) *DeviceUpdate {
	if v != nil {
		_u.SetThingModelID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceUpdate) SetStatus(v device.Status) *DeviceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableStatus(v *device.Status) *DeviceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOnline sets the "online" field.
func (_u *DeviceUpdate) SetOnline(v bool) *DeviceUpdate {
	_u.mutation.SetOnline(v)
	return _u
}

// SetNillableOnline sets the "online" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableOnline(v *bool) *DeviceUpdate {
	if v != nil {
		_u.SetOnline(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DeviceUpdate) SetMetadata(v map[string]interface{}) *DeviceUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *DeviceUpdate) SetLastSeen(v time.Time) *DeviceUpdate {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableLastSeen(v *time.Time) *DeviceUpdate {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// ClearLastSeen clears the value of the "last_seen" field.
func (_u *DeviceUpdate) ClearLastSeen() *DeviceUpdate {
	_u.mutation.ClearLastSeen()
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *DeviceUpdate) SetTenant(v *Tenant) *DeviceUpdate {
	return _u.SetTenantID(v.ID)
}

// SetThingModel sets the "thing_model" edge to the ThingModel entity.
func (_u *DeviceUpdate) SetThingModel(v *ThingModel) *DeviceUpdate {
	return _u.SetThingModelID(v.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *DeviceUpdate) ClearTenant() *DeviceUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearThingModel clears the "thing_model" edge to the ThingModel entity.
func (_u *DeviceUpdate) ClearThingModel() *DeviceUpdate {
	_u.mutation.ClearThingModel()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := device.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`ent: validator failed for field "Device.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelKey(); ok {
		if err := device.ModelKeyValidator(v); err != nil {
			return &ValidationError{Name: "model_key", err: fmt.Errorf(`ent: validator failed for field "Device.model_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := device.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "Device.device_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessKey(); ok {
		if err := device.AccessKeyValidator(v); err != nil {
			return &ValidationError{Name: "access_key", err: fmt.Errorf(`ent: validator failed for field "Device.access_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirmwareVer(); ok {
		if err := device.FirmwareVerValidator(v); err != nil {
			return &ValidationError{Name: "firmware_ver", err: fmt.Errorf(`ent: validator failed for field "Device.firmware_ver": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := device.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Device.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Device.tenant"`)
	}
	if _u.mutation.ThingModelCleared() && len(_u.mutation.ThingModelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Device.thing_model"`)
	}
	return nil
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(device.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelKey(); ok {
		_spec.SetField(device.FieldModelKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKey(); ok {
		_spec.SetField(device.FieldAccessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirmwareVer(); ok {
		_spec.SetField(device.FieldFirmwareVer, field.TypeString, value)
	}
	if value, ok := _u.mutation.PropertiesCfg(); ok {
		_spec.SetField(device.FieldPropertiesCfg, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Online(); ok {
		_spec.SetField(device.FieldOnline, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(device.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(device.FieldLastSeen, field.TypeTime, value)
	}
	if _u.mutation.LastSeenCleared() {
		_spec.ClearField(device.FieldLastSeen, field.TypeTime)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.TenantTable,
			Columns: []string{device.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.TenantTable,
			Columns: []string{device.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThingModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.ThingModelTable,
			Columns: []string{device.ThingModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThingModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.ThingModelTable,
			Columns: []string{device.ThingModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetTenantKey sets the "tenant_key" field.
func (_u *DeviceUpdateOne) SetTenantKey(v string) *DeviceUpdateOne {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableTenantKey(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetModelKey sets the "model_key" field.
func (_u *DeviceUpdateOne) SetModelKey(v string) *DeviceUpdateOne {
	_u.mutation.SetModelKey(v)
	return _u
}

// SetNillableModelKey sets the "model_key" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableModelKey(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetModelKey(*v)
	}
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *DeviceUpdateOne) SetDeviceName(v string) *DeviceUpdateOne {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDeviceName(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetAccessKey sets the "access_key" field.
func (_u *DeviceUpdateOne) SetAccessKey(v string) *DeviceUpdateOne {
	_u.mutation.SetAccessKey(v)
	return _u
}

// SetNillableAccessKey sets the "access_key" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableAccessKey(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetAccessKey(*v)
	}
	return _u
}

// SetFirmwareVer sets the "firmware_ver" field.
func (_u *DeviceUpdateOne) SetFirmwareVer(v string) *DeviceUpdateOne {
	_u.mutation.SetFirmwareVer(v)
	return _u
}

// SetNillableFirmwareVer sets the "firmware_ver" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableFirmwareVer(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetFirmwareVer(*v)
	}
	return _u
}

// SetPropertiesCfg sets the "properties_cfg" field.
func (_u *DeviceUpdateOne) SetPropertiesCfg(v map[string]interface{}) *DeviceUpdateOne {
	_u.mutation.SetPropertiesCfg(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *DeviceUpdateOne) SetTenantID(v int) *DeviceUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableTenantID(v *int) *DeviceUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetThingModelID sets the "thing_model_id" field.
func (_u *DeviceUpdateOne) SetThingModelID(v int) *DeviceUpdateOne {
	_u.mutation.SetThingModelID(v)
	return _u
}

// SetNillableThingModelID sets the "thing_model_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableThingModelID(v *int) *DeviceUpdateOne {
	if v != nil {
		_u.SetThingModelID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeviceUpdateOne) SetStatus(v device.Status) *DeviceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableStatus(v *device.Status) *DeviceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOnline sets the "online" field.
func (_u *DeviceUpdateOne) SetOnline(v bool) *DeviceUpdateOne {
	_u.mutation.SetOnline(v)
	return _u
}

// SetNillableOnline sets the "online" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableOnline(v *bool) *DeviceUpdateOne {
	if v != nil {
		_u.SetOnline(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *DeviceUpdateOne) SetMetadata(v map[string]interface{}) *DeviceUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *DeviceUpdateOne) SetLastSeen(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableLastSeen(v *time.Time) *DeviceUpdateOne {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// ClearLastSeen clears the value of the "last_seen" field.
func (_u *DeviceUpdateOne) ClearLastSeen() *DeviceUpdateOne {
	_u.mutation.ClearLastSeen()
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *DeviceUpdateOne) SetTenant(v *Tenant) *DeviceUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetThingModel sets the "thing_model" edge to the ThingModel entity.
func (_u *DeviceUpdateOne) SetThingModel(v *ThingModel) *DeviceUpdateOne {
	return _u.SetThingModelID(v.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *DeviceUpdateOne) ClearTenant() *DeviceUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearThingModel clears the "thing_model" edge to the ThingModel entity.
func (_u *DeviceUpdateOne) ClearThingModel() *DeviceUpdateOne {
	_u.mutation.ClearThingModel()
	return _u
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := device.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`ent: validator failed for field "Device.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelKey(); ok {
		if err := device.ModelKeyValidator(v); err != nil {
			return &ValidationError{Name: "model_key", err: fmt.Errorf(`ent: validator failed for field "Device.model_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeviceName(); ok {
		if err := device.DeviceNameValidator(v); err != nil {
			return &ValidationError{Name: "device_name", err: fmt.Errorf(`ent: validator failed for field "Device.device_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessKey(); ok {
		if err := device.AccessKeyValidator(v); err != nil {
			return &ValidationError{Name: "access_key", err: fmt.Errorf(`ent: validator failed for field "Device.access_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FirmwareVer(); ok {
		if err := device.FirmwareVerValidator(v); err != nil {
			return &ValidationError{Name: "firmware_ver", err: fmt.Errorf(`ent: validator failed for field "Device.firmware_ver": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := device.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Device.status": %w`, err)}
		}
	}
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Device.tenant"`)
	}
	if _u.mutation.ThingModelCleared() && len(_u.mutation.ThingModelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Device.thing_model"`)
	}
	return nil
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(device.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelKey(); ok {
		_spec.SetField(device.FieldModelKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(device.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKey(); ok {
		_spec.SetField(device.FieldAccessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirmwareVer(); ok {
		_spec.SetField(device.FieldFirmwareVer, field.TypeString, value)
	}
	if value, ok := _u.mutation.PropertiesCfg(); ok {
		_spec.SetField(device.FieldPropertiesCfg, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(device.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Online(); ok {
		_spec.SetField(device.FieldOnline, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(device.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(device.FieldLastSeen, field.TypeTime, value)
	}
	if _u.mutation.LastSeenCleared() {
		_spec.ClearField(device.FieldLastSeen, field.TypeTime)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.TenantTable,
			Columns: []string{device.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.TenantTable,
			Columns: []string{device.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThingModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.ThingModelTable,
			Columns: []string{device.ThingModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThingModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.ThingModelTable,
			Columns: []string{device.ThingModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
