// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Seeker32/AssassinIoT/backend/ent/modelcategory"
	"github.com/Seeker32/AssassinIoT/backend/ent/tenant"
	"github.com/Seeker32/AssassinIoT/backend/ent/thingmodel"
)

// ModelCategoryCreate is the builder for creating a ModelCategory entity.
type ModelCategoryCreate struct {
	config
	mutation *ModelCategoryMutation
	hooks    []Hook
}

// SetTenantKey sets the "tenant_key" field.
func (_c *ModelCategoryCreate) SetTenantKey(v string) *ModelCategoryCreate {
	_c.mutation.SetTenantKey(v)
	return _c
}

// SetCategoryKey sets the "category_key" field.
func (_c *ModelCategoryCreate) SetCategoryKey(v string) *ModelCategoryCreate {
	_c.mutation.SetCategoryKey(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *ModelCategoryCreate) SetDisplayName(v string) *ModelCategoryCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ModelCategoryCreate) SetDescription(v string) *ModelCategoryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ModelCategoryCreate) SetNillableDescription(v *string) *ModelCategoryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *ModelCategoryCreate) SetIcon(v string) *ModelCategoryCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *ModelCategoryCreate) SetNillableIcon(v *string) *ModelCategoryCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ModelCategoryCreate) SetSortOrder(v int) *ModelCategoryCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ModelCategoryCreate) SetNillableSortOrder(v *int) *ModelCategoryCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ModelCategoryCreate) SetTenantID(v int) *ModelCategoryCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ModelCategoryCreate) SetStatus(v modelcategory.Status) *ModelCategoryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ModelCategoryCreate) SetNillableStatus(v *modelcategory.Status) *ModelCategoryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelCategoryCreate) SetCreatedAt(v time.Time) *ModelCategoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelCategoryCreate) SetNillableCreatedAt(v *time.Time) *ModelCategoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelCategoryCreate) SetUpdatedAt(v time.Time) *ModelCategoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelCategoryCreate) SetNillableUpdatedAt(v *time.Time) *ModelCategoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *ModelCategoryCreate) SetTenant(v *Tenant) *ModelCategoryCreate {
	return _c.SetTenantID(v.ID)
}

// AddThingModelIDs adds the "thing_models" edge to the ThingModel entity by IDs.
func (_c *ModelCategoryCreate) AddThingModelIDs(ids ...int) *ModelCategoryCreate {
	_c.mutation.AddThingModelIDs(ids...)
	return _c
}

// AddThingModels adds the "thing_models" edges to the ThingModel entity.
func (_c *ModelCategoryCreate) AddThingModels(v ...*ThingModel) *ModelCategoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddThingModelIDs(ids...)
}

// Mutation returns the ModelCategoryMutation object of the builder.
func (_c *ModelCategoryCreate) Mutation() *ModelCategoryMutation {
	return _c.mutation
}

// Save creates the ModelCategory in the database.
func (_c *ModelCategoryCreate) Save(ctx context.Context) (*ModelCategory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelCategoryCreate) SaveX(ctx context.Context) *ModelCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelCategoryCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := modelcategory.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Icon(); !ok {
		v := modelcategory.DefaultIcon
		_c.mutation.SetIcon(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := modelcategory.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := modelcategory.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelcategory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelcategory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelCategoryCreate) check() error {
	if _, ok := _c.mutation.TenantKey(); !ok {
		return &ValidationError{Name: "tenant_key", err: errors.New(`ent: missing required field "ModelCategory.tenant_key"`)}
	}
	if v, ok := _c.mutation.TenantKey(); ok {
		if err := modelcategory.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`ent: validator failed for field "ModelCategory.tenant_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CategoryKey(); !ok {
		return &ValidationError{Name: "category_key", err: errors.New(`ent: missing required field "ModelCategory.category_key"`)}
	}
	if v, ok := _c.mutation.CategoryKey(); ok {
		if err := modelcategory.CategoryKeyValidator(v); err != nil {
			return &ValidationError{Name: "category_key", err: fmt.Errorf(`ent: validator failed for field "ModelCategory.category_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "ModelCategory.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := modelcategory.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelCategory.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ModelCategory.description"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "ModelCategory.icon"`)}
	}
	if v, ok := _c.mutation.Icon(); ok {
		if err := modelcategory.IconValidator(v); err != nil {
			return &ValidationError{Name: "icon", err: fmt.Errorf(`ent: validator failed for field "ModelCategory.icon": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "ModelCategory.sort_order"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ModelCategory.tenant_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ModelCategory.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := modelcategory.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCategory.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelCategory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelCategory.updated_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "ModelCategory.tenant"`)}
	}
	return nil
}

func (_c *ModelCategoryCreate) sqlSave(ctx context.Context) (*ModelCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelCategoryCreate) createSpec() (*ModelCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelcategory.Table, sqlgraph.NewFieldSpec(modelcategory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantKey(); ok {
		_spec.SetField(modelcategory.FieldTenantKey, field.TypeString, value)
		_node.TenantKey = value
	}
	if value, ok := _c.mutation.CategoryKey(); ok {
		_spec.SetField(modelcategory.FieldCategoryKey, field.TypeString, value)
		_node.CategoryKey = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(modelcategory.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(modelcategory.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(modelcategory.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(modelcategory.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(modelcategory.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelcategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelcategory.TenantTable,
			Columns: []string{modelcategory.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ThingModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcategory.ThingModelsTable,
			Columns: []string{modelcategory.ThingModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ModelCategoryCreateBulk is the builder for creating many ModelCategory entities in bulk.
type ModelCategoryCreateBulk struct {
	config
	err      error
	builders []*ModelCategoryCreate
}

// Save creates the ModelCategory entities in the database.
func (_c *ModelCategoryCreateBulk) Save(ctx context.Context) ([]*ModelCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelCategoryCreateBulk) SaveX(ctx context.Context) []*ModelCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
