// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Seeker32/AssassinIoT/backend/ent/mqttuser"
)

// MqttUserCreate is the builder for creating a MqttUser entity.
type MqttUserCreate struct {
	config
	mutation *MqttUserMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MqttUserCreate) SetDeletedAt(v time.Time) *MqttUserCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MqttUserCreate) SetNillableDeletedAt(v *time.Time) *MqttUserCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *MqttUserCreate) SetUsername(v string) *MqttUserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *MqttUserCreate) SetPasswordHash(v string) *MqttUserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetSalt sets the "salt" field.
func (_c *MqttUserCreate) SetSalt(v string) *MqttUserCreate {
	_c.mutation.SetSalt(v)
	return _c
}

// SetIsSuperuser sets the "is_superuser" field.
func (_c *MqttUserCreate) SetIsSuperuser(v bool) *MqttUserCreate {
	_c.mutation.SetIsSuperuser(v)
	return _c
}

// SetNillableIsSuperuser sets the "is_superuser" field if the given value is not nil.
func (_c *MqttUserCreate) SetNillableIsSuperuser(v *bool) *MqttUserCreate {
	if v != nil {
		_c.SetIsSuperuser(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *MqttUserCreate) SetCreated(v time.Time) *MqttUserCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetNillableCreated sets the "created" field if the given value is not nil.
func (_c *MqttUserCreate) SetNillableCreated(v *time.Time) *MqttUserCreate {
	if v != nil {
		_c.SetCreated(*v)
	}
	return _c
}

// Mutation returns the MqttUserMutation object of the builder.
func (_c *MqttUserCreate) Mutation() *MqttUserMutation {
	return _c.mutation
}

// Save creates the MqttUser in the database.
func (_c *MqttUserCreate) Save(ctx context.Context) (*MqttUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MqttUserCreate) SaveX(ctx context.Context) *MqttUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MqttUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MqttUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MqttUserCreate) defaults() {
	if _, ok := _c.mutation.IsSuperuser(); !ok {
		v := mqttuser.DefaultIsSuperuser
		_c.mutation.SetIsSuperuser(v)
	}
	if _, ok := _c.mutation.Created(); !ok {
		v := mqttuser.DefaultCreated()
		_c.mutation.SetCreated(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MqttUserCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "MqttUser.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := mqttuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "MqttUser.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "MqttUser.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := mqttuser.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "MqttUser.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Salt(); !ok {
		return &ValidationError{Name: "salt", err: errors.New(`ent: missing required field "MqttUser.salt"`)}
	}
	if v, ok := _c.mutation.Salt(); ok {
		if err := mqttuser.SaltValidator(v); err != nil {
			return &ValidationError{Name: "salt", err: fmt.Errorf(`ent: validator failed for field "MqttUser.salt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsSuperuser(); !ok {
		return &ValidationError{Name: "is_superuser", err: errors.New(`ent: missing required field "MqttUser.is_superuser"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "MqttUser.created"`)}
	}
	return nil
}

func (_c *MqttUserCreate) sqlSave(ctx context.Context) (*MqttUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MqttUserCreate) createSpec() (*MqttUser, *sqlgraph.CreateSpec) {
	var (
		_node = &MqttUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mqttuser.Table, sqlgraph.NewFieldSpec(mqttuser.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(mqttuser.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(mqttuser.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(mqttuser.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.Salt(); ok {
		_spec.SetField(mqttuser.FieldSalt, field.TypeString, value)
		_node.Salt = value
	}
	if value, ok := _c.mutation.IsSuperuser(); ok {
		_spec.SetField(mqttuser.FieldIsSuperuser, field.TypeBool, value)
		_node.IsSuperuser = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(mqttuser.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	return _node, _spec
}

// MqttUserCreateBulk is the builder for creating many MqttUser entities in bulk.
type MqttUserCreateBulk struct {
	config
	err      error
	builders []*MqttUserCreate
}

// Save creates the MqttUser entities in the database.
func (_c *MqttUserCreateBulk) Save(ctx context.Context) ([]*MqttUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MqttUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MqttUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MqttUserCreateBulk) SaveX(ctx context.Context) []*MqttUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MqttUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MqttUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
