// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Seeker32/AssassinIoT/backend/ent/mqttuser"
)

// MqttUser is the model entity for the MqttUser schema.
type MqttUser struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 软删除时间，非空表示已删除
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// MQTT 客户端用户名
	Username string `json:"username,omitempty"`
	// 密码哈希值 (sha256(password + salt))
	PasswordHash string `json:"password_hash,omitempty"`
	// 密码盐值，每个用户随机生成
	Salt string `json:"salt,omitempty"`
	// 是否为超级用户
	IsSuperuser bool `json:"is_superuser,omitempty"`
	// 创建时间
	Created      time.Time `json:"created,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MqttUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mqttuser.FieldIsSuperuser:
			values[i] = new(sql.NullBool)
		case mqttuser.FieldID:
			values[i] = new(sql.NullInt64)
		case mqttuser.FieldUsername, mqttuser.FieldPasswordHash, mqttuser.FieldSalt:
			values[i] = new(sql.NullString)
		case mqttuser.FieldDeletedAt, mqttuser.FieldCreated:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MqttUser fields.
func (_m *MqttUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mqttuser.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mqttuser.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case mqttuser.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case mqttuser.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case mqttuser.FieldSalt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field salt", values[i])
			} else if value.Valid {
				_m.Salt = value.String
			}
		case mqttuser.FieldIsSuperuser:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_superuser", values[i])
			} else if value.Valid {
				_m.IsSuperuser = value.Bool
			}
		case mqttuser.FieldCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created", values[i])
			} else if value.Valid {
				_m.Created = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MqttUser.
// This includes values selected through modifiers, order, etc.
func (_m *MqttUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MqttUser.
// Note that you need to call MqttUser.Unwrap() before calling this method if this MqttUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MqttUser) Update() *MqttUserUpdateOne {
	return NewMqttUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MqttUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MqttUser) Unwrap() *MqttUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MqttUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MqttUser) String() string {
	var builder strings.Builder
	builder.WriteString("MqttUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(_m.PasswordHash)
	builder.WriteString(", ")
	builder.WriteString("salt=")
	builder.WriteString(_m.Salt)
	builder.WriteString(", ")
	builder.WriteString("is_superuser=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSuperuser))
	builder.WriteString(", ")
	builder.WriteString("created=")
	builder.WriteString(_m.Created.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MqttUsers is a parsable slice of MqttUser.
type MqttUsers []*MqttUser
