// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Seeker32/AssassinIoT/backend/ent/mqttuser"
	"github.com/Seeker32/AssassinIoT/backend/ent/predicate"
)

// MqttUserUpdate is the builder for updating MqttUser entities.
type MqttUserUpdate struct {
	config
	hooks    []Hook
	mutation *MqttUserMutation
}

// Where appends a list predicates to the MqttUserUpdate builder.
func (_u *MqttUserUpdate) Where(ps ...predicate.MqttUser) *MqttUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MqttUserUpdate) SetDeletedAt(v time.Time) *MqttUserUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MqttUserUpdate) SetNillableDeletedAt(v *time.Time) *MqttUserUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MqttUserUpdate) ClearDeletedAt() *MqttUserUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUsername sets the "username" field.
func (_u *MqttUserUpdate) SetUsername(v string) *MqttUserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *MqttUserUpdate) SetNillableUsername(v *string) *MqttUserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *MqttUserUpdate) SetPasswordHash(v string) *MqttUserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *MqttUserUpdate) SetNillablePasswordHash(v *string) *MqttUserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetSalt sets the "salt" field.
func (_u *MqttUserUpdate) SetSalt(v string) *MqttUserUpdate {
	_u.mutation.SetSalt(v)
	return _u
}

// SetNillableSalt sets the "salt" field if the given value is not nil.
func (_u *MqttUserUpdate) SetNillableSalt(v *string) *MqttUserUpdate {
	if v != nil {
		_u.SetSalt(*v)
	}
	return _u
}

// SetIsSuperuser sets the "is_superuser" field.
func (_u *MqttUserUpdate) SetIsSuperuser(v bool) *MqttUserUpdate {
	_u.mutation.SetIsSuperuser(v)
	return _u
}

// SetNillableIsSuperuser sets the "is_superuser" field if the given value is not nil.
func (_u *MqttUserUpdate) SetNillableIsSuperuser(v *bool) *MqttUserUpdate {
	if v != nil {
		_u.SetIsSuperuser(*v)
	}
	return _u
}

// Mutation returns the MqttUserMutation object of the builder.
func (_u *MqttUserUpdate) Mutation() *MqttUserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MqttUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MqttUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MqttUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MqttUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MqttUserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := mqttuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "MqttUser.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := mqttuser.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "MqttUser.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Salt(); ok {
		if err := mqttuser.SaltValidator(v); err != nil {
			return &ValidationError{Name: "salt", err: fmt.Errorf(`ent: validator failed for field "MqttUser.salt": %w`, err)}
		}
	}
	return nil
}

func (_u *MqttUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mqttuser.Table, mqttuser.Columns, sqlgraph.NewFieldSpec(mqttuser.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mqttuser.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mqttuser.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(mqttuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(mqttuser.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Salt(); ok {
		_spec.SetField(mqttuser.FieldSalt, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSuperuser(); ok {
		_spec.SetField(mqttuser.FieldIsSuperuser, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mqttuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MqttUserUpdateOne is the builder for updating a single MqttUser entity.
type MqttUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MqttUserMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *MqttUserUpdateOne) SetDeletedAt(v time.Time) *MqttUserUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *MqttUserUpdateOne) SetNillableDeletedAt(v *time.Time) *MqttUserUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *MqttUserUpdateOne) ClearDeletedAt() *MqttUserUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUsername sets the "username" field.
func (_u *MqttUserUpdateOne) SetUsername(v string) *MqttUserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *MqttUserUpdateOne) SetNillableUsername(v *string) *MqttUserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *MqttUserUpdateOne) SetPasswordHash(v string) *MqttUserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *MqttUserUpdateOne) SetNillablePasswordHash(v *string) *MqttUserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetSalt sets the "salt" field.
func (_u *MqttUserUpdateOne) SetSalt(v string) *MqttUserUpdateOne {
	_u.mutation.SetSalt(v)
	return _u
}

// SetNillableSalt sets the "salt" field if the given value is not nil.
func (_u *MqttUserUpdateOne) SetNillableSalt(v *string) *MqttUserUpdateOne {
	if v != nil {
		_u.SetSalt(*v)
	}
	return _u
}

// SetIsSuperuser sets the "is_superuser" field.
func (_u *MqttUserUpdateOne) SetIsSuperuser(v bool) *MqttUserUpdateOne {
	_u.mutation.SetIsSuperuser(v)
	return _u
}

// SetNillableIsSuperuser sets the "is_superuser" field if the given value is not nil.
func (_u *MqttUserUpdateOne) SetNillableIsSuperuser(v *bool) *MqttUserUpdateOne {
	if v != nil {
		_u.SetIsSuperuser(*v)
	}
	return _u
}

// Mutation returns the MqttUserMutation object of the builder.
func (_u *MqttUserUpdateOne) Mutation() *MqttUserMutation {
	return _u.mutation
}

// Where appends a list predicates to the MqttUserUpdate builder.
func (_u *MqttUserUpdateOne) Where(ps ...predicate.MqttUser) *MqttUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MqttUserUpdateOne) Select(field string, fields ...string) *MqttUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MqttUser entity.
func (_u *MqttUserUpdateOne) Save(ctx context.Context) (*MqttUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MqttUserUpdateOne) SaveX(ctx context.Context) *MqttUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MqttUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MqttUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MqttUserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := mqttuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "MqttUser.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := mqttuser.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "MqttUser.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Salt(); ok {
		if err := mqttuser.SaltValidator(v); err != nil {
			return &ValidationError{Name: "salt", err: fmt.Errorf(`ent: validator failed for field "MqttUser.salt": %w`, err)}
		}
	}
	return nil
}

func (_u *MqttUserUpdateOne) sqlSave(ctx context.Context) (_node *MqttUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mqttuser.Table, mqttuser.Columns, sqlgraph.NewFieldSpec(mqttuser.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MqttUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mqttuser.FieldID)
		for _, f := range fields {
			if !mqttuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mqttuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(mqttuser.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(mqttuser.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(mqttuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(mqttuser.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Salt(); ok {
		_spec.SetField(mqttuser.FieldSalt, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSuperuser(); ok {
		_spec.SetField(mqttuser.FieldIsSuperuser, field.TypeBool, value)
	}
	_node = &MqttUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mqttuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
