// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Seeker32/AssassinIoT/ent/device"
	"github.com/Seeker32/AssassinIoT/ent/devicetelemetry"
	"github.com/Seeker32/AssassinIoT/ent/modelcategory"
	"github.com/Seeker32/AssassinIoT/ent/schema"
	"github.com/Seeker32/AssassinIoT/ent/tenant"
	"github.com/Seeker32/AssassinIoT/ent/thingmodel"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescTenantKey is the schema descriptor for tenant_key field.
	deviceDescTenantKey := deviceFields[1].Descriptor()
	// device.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	device.TenantKeyValidator = func() func(string) error {
		validators := deviceDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// deviceDescModelKey is the schema descriptor for model_key field.
	deviceDescModelKey := deviceFields[2].Descriptor()
	// device.ModelKeyValidator is a validator for the "model_key" field. It is called by the builders before save.
	device.ModelKeyValidator = func() func(string) error {
		validators := deviceDescModelKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model_key string) error {
			for _, fn := range fns {
				if err := fn(model_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// deviceDescDeviceName is the schema descriptor for device_name field.
	deviceDescDeviceName := deviceFields[3].Descriptor()
	// device.DefaultDeviceName holds the default value on creation for the device_name field.
	device.DefaultDeviceName = deviceDescDeviceName.Default.(string)
	// device.DeviceNameValidator is a validator for the "device_name" field. It is called by the builders before save.
	device.DeviceNameValidator = deviceDescDeviceName.Validators[0].(func(string) error)
	// deviceDescAccessKey is the schema descriptor for access_key field.
	deviceDescAccessKey := deviceFields[4].Descriptor()
	// device.AccessKeyValidator is a validator for the "access_key" field. It is called by the builders before save.
	device.AccessKeyValidator = func() func(string) error {
		validators := deviceDescAccessKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(access_key string) error {
			for _, fn := range fns {
				if err := fn(access_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// deviceDescFirmwareVer is the schema descriptor for firmware_ver field.
	deviceDescFirmwareVer := deviceFields[5].Descriptor()
	// device.DefaultFirmwareVer holds the default value on creation for the firmware_ver field.
	device.DefaultFirmwareVer = deviceDescFirmwareVer.Default.(string)
	// device.FirmwareVerValidator is a validator for the "firmware_ver" field. It is called by the builders before save.
	device.FirmwareVerValidator = deviceDescFirmwareVer.Validators[0].(func(string) error)
	// deviceDescPropertiesCfg is the schema descriptor for properties_cfg field.
	deviceDescPropertiesCfg := deviceFields[6].Descriptor()
	// device.DefaultPropertiesCfg holds the default value on creation for the properties_cfg field.
	device.DefaultPropertiesCfg = deviceDescPropertiesCfg.Default.(map[string]interface{})
	// deviceDescOnline is the schema descriptor for online field.
	deviceDescOnline := deviceFields[10].Descriptor()
	// device.DefaultOnline holds the default value on creation for the online field.
	device.DefaultOnline = deviceDescOnline.Default.(bool)
	// deviceDescMetadata is the schema descriptor for metadata field.
	deviceDescMetadata := deviceFields[11].Descriptor()
	// device.DefaultMetadata holds the default value on creation for the metadata field.
	device.DefaultMetadata = deviceDescMetadata.Default.(map[string]interface{})
	// deviceDescCreatedAt is the schema descriptor for created_at field.
	deviceDescCreatedAt := deviceFields[12].Descriptor()
	// device.DefaultCreatedAt holds the default value on creation for the created_at field.
	device.DefaultCreatedAt = deviceDescCreatedAt.Default.(func() time.Time)
	// deviceDescUpdatedAt is the schema descriptor for updated_at field.
	deviceDescUpdatedAt := deviceFields[13].Descriptor()
	// device.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	device.DefaultUpdatedAt = deviceDescUpdatedAt.Default.(func() time.Time)
	// device.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	device.UpdateDefaultUpdatedAt = deviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deviceDescID is the schema descriptor for id field.
	deviceDescID := deviceFields[0].Descriptor()
	// device.IDValidator is a validator for the "id" field. It is called by the builders before save.
	device.IDValidator = deviceDescID.Validators[0].(func(string) error)
	devicetelemetryFields := schema.DeviceTelemetry{}.Fields()
	_ = devicetelemetryFields
	// devicetelemetryDescCreatedAt is the schema descriptor for created_at field.
	devicetelemetryDescCreatedAt := devicetelemetryFields[10].Descriptor()
	// devicetelemetry.DefaultCreatedAt holds the default value on creation for the created_at field.
	devicetelemetry.DefaultCreatedAt = devicetelemetryDescCreatedAt.Default.(func() time.Time)
	modelcategoryFields := schema.ModelCategory{}.Fields()
	_ = modelcategoryFields
	// modelcategoryDescTenantKey is the schema descriptor for tenant_key field.
	modelcategoryDescTenantKey := modelcategoryFields[0].Descriptor()
	// modelcategory.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	modelcategory.TenantKeyValidator = func() func(string) error {
		validators := modelcategoryDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// modelcategoryDescCategoryKey is the schema descriptor for category_key field.
	modelcategoryDescCategoryKey := modelcategoryFields[1].Descriptor()
	// modelcategory.CategoryKeyValidator is a validator for the "category_key" field. It is called by the builders before save.
	modelcategory.CategoryKeyValidator = func() func(string) error {
		validators := modelcategoryDescCategoryKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(category_key string) error {
			for _, fn := range fns {
				if err := fn(category_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// modelcategoryDescDisplayName is the schema descriptor for display_name field.
	modelcategoryDescDisplayName := modelcategoryFields[2].Descriptor()
	// modelcategory.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	modelcategory.DisplayNameValidator = func() func(string) error {
		validators := modelcategoryDescDisplayName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(display_name string) error {
			for _, fn := range fns {
				if err := fn(display_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// modelcategoryDescDescription is the schema descriptor for description field.
	modelcategoryDescDescription := modelcategoryFields[3].Descriptor()
	// modelcategory.DefaultDescription holds the default value on creation for the description field.
	modelcategory.DefaultDescription = modelcategoryDescDescription.Default.(string)
	// modelcategoryDescIcon is the schema descriptor for icon field.
	modelcategoryDescIcon := modelcategoryFields[4].Descriptor()
	// modelcategory.DefaultIcon holds the default value on creation for the icon field.
	modelcategory.DefaultIcon = modelcategoryDescIcon.Default.(string)
	// modelcategory.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	modelcategory.IconValidator = modelcategoryDescIcon.Validators[0].(func(string) error)
	// modelcategoryDescSortOrder is the schema descriptor for sort_order field.
	modelcategoryDescSortOrder := modelcategoryFields[5].Descriptor()
	// modelcategory.DefaultSortOrder holds the default value on creation for the sort_order field.
	modelcategory.DefaultSortOrder = modelcategoryDescSortOrder.Default.(int)
	// modelcategoryDescCreatedAt is the schema descriptor for created_at field.
	modelcategoryDescCreatedAt := modelcategoryFields[8].Descriptor()
	// modelcategory.DefaultCreatedAt holds the default value on creation for the created_at field.
	modelcategory.DefaultCreatedAt = modelcategoryDescCreatedAt.Default.(func() time.Time)
	// modelcategoryDescUpdatedAt is the schema descriptor for updated_at field.
	modelcategoryDescUpdatedAt := modelcategoryFields[9].Descriptor()
	// modelcategory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	modelcategory.DefaultUpdatedAt = modelcategoryDescUpdatedAt.Default.(func() time.Time)
	// modelcategory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	modelcategory.UpdateDefaultUpdatedAt = modelcategoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescTenantKey is the schema descriptor for tenant_key field.
	tenantDescTenantKey := tenantFields[0].Descriptor()
	// tenant.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	tenant.TenantKeyValidator = func() func(string) error {
		validators := tenantDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = func() func(string) error {
		validators := tenantDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescDescription is the schema descriptor for description field.
	tenantDescDescription := tenantFields[2].Descriptor()
	// tenant.DefaultDescription holds the default value on creation for the description field.
	tenant.DefaultDescription = tenantDescDescription.Default.(string)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[4].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[5].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	thingmodelFields := schema.ThingModel{}.Fields()
	_ = thingmodelFields
	// thingmodelDescModelKey is the schema descriptor for model_key field.
	thingmodelDescModelKey := thingmodelFields[0].Descriptor()
	// thingmodel.ModelKeyValidator is a validator for the "model_key" field. It is called by the builders before save.
	thingmodel.ModelKeyValidator = func() func(string) error {
		validators := thingmodelDescModelKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(model_key string) error {
			for _, fn := range fns {
				if err := fn(model_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// thingmodelDescTenantKey is the schema descriptor for tenant_key field.
	thingmodelDescTenantKey := thingmodelFields[1].Descriptor()
	// thingmodel.TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	thingmodel.TenantKeyValidator = func() func(string) error {
		validators := thingmodelDescTenantKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(tenant_key string) error {
			for _, fn := range fns {
				if err := fn(tenant_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// thingmodelDescName is the schema descriptor for name field.
	thingmodelDescName := thingmodelFields[2].Descriptor()
	// thingmodel.NameValidator is a validator for the "name" field. It is called by the builders before save.
	thingmodel.NameValidator = func() func(string) error {
		validators := thingmodelDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// thingmodelDescDescription is the schema descriptor for description field.
	thingmodelDescDescription := thingmodelFields[3].Descriptor()
	// thingmodel.DefaultDescription holds the default value on creation for the description field.
	thingmodel.DefaultDescription = thingmodelDescDescription.Default.(string)
	// thingmodelDescCategory is the schema descriptor for category field.
	thingmodelDescCategory := thingmodelFields[4].Descriptor()
	// thingmodel.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	thingmodel.CategoryValidator = func() func(string) error {
		validators := thingmodelDescCategory.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(category string) error {
			for _, fn := range fns {
				if err := fn(category); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// thingmodelDescProperties is the schema descriptor for properties field.
	thingmodelDescProperties := thingmodelFields[5].Descriptor()
	// thingmodel.DefaultProperties holds the default value on creation for the properties field.
	thingmodel.DefaultProperties = thingmodelDescProperties.Default.(map[string]interface{})
	// thingmodelDescServices is the schema descriptor for services field.
	thingmodelDescServices := thingmodelFields[6].Descriptor()
	// thingmodel.DefaultServices holds the default value on creation for the services field.
	thingmodel.DefaultServices = thingmodelDescServices.Default.(map[string]interface{})
	// thingmodelDescEvents is the schema descriptor for events field.
	thingmodelDescEvents := thingmodelFields[7].Descriptor()
	// thingmodel.DefaultEvents holds the default value on creation for the events field.
	thingmodel.DefaultEvents = thingmodelDescEvents.Default.(map[string]interface{})
	// thingmodelDescVersion is the schema descriptor for version field.
	thingmodelDescVersion := thingmodelFields[8].Descriptor()
	// thingmodel.DefaultVersion holds the default value on creation for the version field.
	thingmodel.DefaultVersion = thingmodelDescVersion.Default.(string)
	// thingmodel.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	thingmodel.VersionValidator = thingmodelDescVersion.Validators[0].(func(string) error)
	// thingmodelDescCreatedAt is the schema descriptor for created_at field.
	thingmodelDescCreatedAt := thingmodelFields[12].Descriptor()
	// thingmodel.DefaultCreatedAt holds the default value on creation for the created_at field.
	thingmodel.DefaultCreatedAt = thingmodelDescCreatedAt.Default.(func() time.Time)
	// thingmodelDescUpdatedAt is the schema descriptor for updated_at field.
	thingmodelDescUpdatedAt := thingmodelFields[13].Descriptor()
	// thingmodel.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	thingmodel.DefaultUpdatedAt = thingmodelDescUpdatedAt.Default.(func() time.Time)
	// thingmodel.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	thingmodel.UpdateDefaultUpdatedAt = thingmodelDescUpdatedAt.UpdateDefault.(func() time.Time)
}
