// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Seeker32/AssassinIoT/backend/ent/modelcategory"
	"github.com/Seeker32/AssassinIoT/backend/ent/tenant"
	"github.com/Seeker32/AssassinIoT/backend/ent/thingmodel"
)

// ThingModel is the model entity for the ThingModel schema.
type ThingModel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 模型标识，如 temp_sensor_v1、smart_lock_v2
	ModelKey string `json:"model_key,omitempty"`
	// 所属租户
	TenantKey string `json:"tenant_key,omitempty"`
	// 物模型名称
	Name string `json:"name,omitempty"`
	// 描述信息
	Description string `json:"description,omitempty"`
	// 设备品类，引用 model_categories.category_key
	Category string `json:"category,omitempty"`
	// 属性定义（JSON Schema），描述设备上报的遥测数据点
	Properties map[string]interface{} `json:"properties,omitempty"`
	// 服务定义，描述可下发给设备的指令及输入输出参数
	Services map[string]interface{} `json:"services,omitempty"`
	// 事件定义，描述设备可上报的事件类型及负载结构
	Events map[string]interface{} `json:"events,omitempty"`
	// 模型版本号，支持平滑升级
	Version string `json:"version,omitempty"`
	// 租户 ID 外键
	TenantID int `json:"tenant_id,omitempty"`
	// 物模型分类 ID 外键
	ModelCategoryID int `json:"model_category_id,omitempty"`
	// 状态：active=启用, deprecated=已废弃但已有设备仍可用, disabled=禁用
	Status thingmodel.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ThingModelQuery when eager-loading is set.
	Edges        ThingModelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ThingModelEdges holds the relations/edges for other nodes in the graph.
type ThingModelEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// ModelCategory holds the value of the model_category edge.
	ModelCategory *ModelCategory `json:"model_category,omitempty"`
	// Devices holds the value of the devices edge.
	Devices []*Device `json:"devices,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ThingModelEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// ModelCategoryOrErr returns the ModelCategory value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ThingModelEdges) ModelCategoryOrErr() (*ModelCategory, error) {
	if e.ModelCategory != nil {
		return e.ModelCategory, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: modelcategory.Label}
	}
	return nil, &NotLoadedError{edge: "model_category"}
}

// DevicesOrErr returns the Devices value or an error if the edge
// was not loaded in eager-loading.
func (e ThingModelEdges) DevicesOrErr() ([]*Device, error) {
	if e.loadedTypes[2] {
		return e.Devices, nil
	}
	return nil, &NotLoadedError{edge: "devices"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ThingModel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case thingmodel.FieldProperties, thingmodel.FieldServices, thingmodel.FieldEvents:
			values[i] = new([]byte)
		case thingmodel.FieldID, thingmodel.FieldTenantID, thingmodel.FieldModelCategoryID:
			values[i] = new(sql.NullInt64)
		case thingmodel.FieldModelKey, thingmodel.FieldTenantKey, thingmodel.FieldName, thingmodel.FieldDescription, thingmodel.FieldCategory, thingmodel.FieldVersion, thingmodel.FieldStatus:
			values[i] = new(sql.NullString)
		case thingmodel.FieldCreatedAt, thingmodel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ThingModel fields.
func (_m *ThingModel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case thingmodel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case thingmodel.FieldModelKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_key", values[i])
			} else if value.Valid {
				_m.ModelKey = value.String
			}
		case thingmodel.FieldTenantKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_key", values[i])
			} else if value.Valid {
				_m.TenantKey = value.String
			}
		case thingmodel.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case thingmodel.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case thingmodel.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case thingmodel.FieldProperties:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field properties", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Properties); err != nil {
					return fmt.Errorf("unmarshal field properties: %w", err)
				}
			}
		case thingmodel.FieldServices:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field services", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Services); err != nil {
					return fmt.Errorf("unmarshal field services: %w", err)
				}
			}
		case thingmodel.FieldEvents:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field events", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Events); err != nil {
					return fmt.Errorf("unmarshal field events: %w", err)
				}
			}
		case thingmodel.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case thingmodel.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case thingmodel.FieldModelCategoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field model_category_id", values[i])
			} else if value.Valid {
				_m.ModelCategoryID = int(value.Int64)
			}
		case thingmodel.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = thingmodel.Status(value.String)
			}
		case thingmodel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case thingmodel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ThingModel.
// This includes values selected through modifiers, order, etc.
func (_m *ThingModel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the ThingModel entity.
func (_m *ThingModel) QueryTenant() *TenantQuery {
	return NewThingModelClient(_m.config).QueryTenant(_m)
}

// QueryModelCategory queries the "model_category" edge of the ThingModel entity.
func (_m *ThingModel) QueryModelCategory() *ModelCategoryQuery {
	return NewThingModelClient(_m.config).QueryModelCategory(_m)
}

// QueryDevices queries the "devices" edge of the ThingModel entity.
func (_m *ThingModel) QueryDevices() *DeviceQuery {
	return NewThingModelClient(_m.config).QueryDevices(_m)
}

// Update returns a builder for updating this ThingModel.
// Note that you need to call ThingModel.Unwrap() before calling this method if this ThingModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ThingModel) Update() *ThingModelUpdateOne {
	return NewThingModelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ThingModel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ThingModel) Unwrap() *ThingModel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ThingModel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ThingModel) String() string {
	var builder strings.Builder
	builder.WriteString("ThingModel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("model_key=")
	builder.WriteString(_m.ModelKey)
	builder.WriteString(", ")
	builder.WriteString("tenant_key=")
	builder.WriteString(_m.TenantKey)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("properties=")
	builder.WriteString(fmt.Sprintf("%v", _m.Properties))
	builder.WriteString(", ")
	builder.WriteString("services=")
	builder.WriteString(fmt.Sprintf("%v", _m.Services))
	builder.WriteString(", ")
	builder.WriteString("events=")
	builder.WriteString(fmt.Sprintf("%v", _m.Events))
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("model_category_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelCategoryID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ThingModels is a parsable slice of ThingModel.
type ThingModels []*ThingModel
