// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Seeker32/AssassinIoT/ent/device"
	"github.com/Seeker32/AssassinIoT/ent/modelcategory"
	"github.com/Seeker32/AssassinIoT/ent/tenant"
	"github.com/Seeker32/AssassinIoT/ent/thingmodel"
)

// ThingModelCreate is the builder for creating a ThingModel entity.
type ThingModelCreate struct {
	config
	mutation *ThingModelMutation
	hooks    []Hook
}

// SetModelKey sets the "model_key" field.
func (_c *ThingModelCreate) SetModelKey(v string) *ThingModelCreate {
	_c.mutation.SetModelKey(v)
	return _c
}

// SetTenantKey sets the "tenant_key" field.
func (_c *ThingModelCreate) SetTenantKey(v string) *ThingModelCreate {
	_c.mutation.SetTenantKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ThingModelCreate) SetName(v string) *ThingModelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ThingModelCreate) SetDescription(v string) *ThingModelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ThingModelCreate) SetNillableDescription(v *string) *ThingModelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *ThingModelCreate) SetCategory(v string) *ThingModelCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetProperties sets the "properties" field.
func (_c *ThingModelCreate) SetProperties(v map[string]interface{}) *ThingModelCreate {
	_c.mutation.SetProperties(v)
	return _c
}

// SetServices sets the "services" field.
func (_c *ThingModelCreate) SetServices(v map[string]interface{}) *ThingModelCreate {
	_c.mutation.SetServices(v)
	return _c
}

// SetEvents sets the "events" field.
func (_c *ThingModelCreate) SetEvents(v map[string]interface{}) *ThingModelCreate {
	_c.mutation.SetEvents(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ThingModelCreate) SetVersion(v string) *ThingModelCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ThingModelCreate) SetNillableVersion(v *string) *ThingModelCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ThingModelCreate) SetTenantID(v int) *ThingModelCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetModelCategoryID sets the "model_category_id" field.
func (_c *ThingModelCreate) SetModelCategoryID(v int) *ThingModelCreate {
	_c.mutation.SetModelCategoryID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ThingModelCreate) SetStatus(v thingmodel.Status) *ThingModelCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ThingModelCreate) SetNillableStatus(v *thingmodel.Status) *ThingModelCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ThingModelCreate) SetCreatedAt(v time.Time) *ThingModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ThingModelCreate) SetNillableCreatedAt(v *time.Time) *ThingModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ThingModelCreate) SetUpdatedAt(v time.Time) *ThingModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ThingModelCreate) SetNillableUpdatedAt(v *time.Time) *ThingModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *ThingModelCreate) SetTenant(v *Tenant) *ThingModelCreate {
	return _c.SetTenantID(v.ID)
}

// SetModelCategory sets the "model_category" edge to the ModelCategory entity.
func (_c *ThingModelCreate) SetModelCategory(v *ModelCategory) *ThingModelCreate {
	return _c.SetModelCategoryID(v.ID)
}

// AddDeviceIDs adds the "devices" edge to the Device entity by IDs.
func (_c *ThingModelCreate) AddDeviceIDs(ids ...string) *ThingModelCreate {
	_c.mutation.AddDeviceIDs(ids...)
	return _c
}

// AddDevices adds the "devices" edges to the Device entity.
func (_c *ThingModelCreate) AddDevices(v ...*Device) *ThingModelCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeviceIDs(ids...)
}

// Mutation returns the ThingModelMutation object of the builder.
func (_c *ThingModelCreate) Mutation() *ThingModelMutation {
	return _c.mutation
}

// Save creates the ThingModel in the database.
func (_c *ThingModelCreate) Save(ctx context.Context) (*ThingModel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ThingModelCreate) SaveX(ctx context.Context) *ThingModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThingModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThingModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ThingModelCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := thingmodel.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Properties(); !ok {
		v := thingmodel.DefaultProperties
		_c.mutation.SetProperties(v)
	}
	if _, ok := _c.mutation.Services(); !ok {
		v := thingmodel.DefaultServices
		_c.mutation.SetServices(v)
	}
	if _, ok := _c.mutation.Events(); !ok {
		v := thingmodel.DefaultEvents
		_c.mutation.SetEvents(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := thingmodel.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := thingmodel.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := thingmodel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := thingmodel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ThingModelCreate) check() error {
	if _, ok := _c.mutation.ModelKey(); !ok {
		return &ValidationError{Name: "model_key", err: errors.New(`ent: missing required field "ThingModel.model_key"`)}
	}
	if v, ok := _c.mutation.ModelKey(); ok {
		if err := thingmodel.ModelKeyValidator(v); err != nil {
			return &ValidationError{Name: "model_key", err: fmt.Errorf(`ent: validator failed for field "ThingModel.model_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantKey(); !ok {
		return &ValidationError{Name: "tenant_key", err: errors.New(`ent: missing required field "ThingModel.tenant_key"`)}
	}
	if v, ok := _c.mutation.TenantKey(); ok {
		if err := thingmodel.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`ent: validator failed for field "ThingModel.tenant_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ThingModel.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := thingmodel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ThingModel.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ThingModel.description"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "ThingModel.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := thingmodel.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ThingModel.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Properties(); !ok {
		return &ValidationError{Name: "properties", err: errors.New(`ent: missing required field "ThingModel.properties"`)}
	}
	if _, ok := _c.mutation.Services(); !ok {
		return &ValidationError{Name: "services", err: errors.New(`ent: missing required field "ThingModel.services"`)}
	}
	if _, ok := _c.mutation.Events(); !ok {
		return &ValidationError{Name: "events", err: errors.New(`ent: missing required field "ThingModel.events"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ThingModel.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := thingmodel.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "ThingModel.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ThingModel.tenant_id"`)}
	}
	if _, ok := _c.mutation.ModelCategoryID(); !ok {
		return &ValidationError{Name: "model_category_id", err: errors.New(`ent: missing required field "ThingModel.model_category_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ThingModel.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := thingmodel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ThingModel.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ThingModel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ThingModel.updated_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "ThingModel.tenant"`)}
	}
	if len(_c.mutation.ModelCategoryIDs()) == 0 {
		return &ValidationError{Name: "model_category", err: errors.New(`ent: missing required edge "ThingModel.model_category"`)}
	}
	return nil
}

func (_c *ThingModelCreate) sqlSave(ctx context.Context) (*ThingModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ThingModelCreate) createSpec() (*ThingModel, *sqlgraph.CreateSpec) {
	var (
		_node = &ThingModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(thingmodel.Table, sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ModelKey(); ok {
		_spec.SetField(thingmodel.FieldModelKey, field.TypeString, value)
		_node.ModelKey = value
	}
	if value, ok := _c.mutation.TenantKey(); ok {
		_spec.SetField(thingmodel.FieldTenantKey, field.TypeString, value)
		_node.TenantKey = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(thingmodel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(thingmodel.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(thingmodel.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Properties(); ok {
		_spec.SetField(thingmodel.FieldProperties, field.TypeJSON, value)
		_node.Properties = value
	}
	if value, ok := _c.mutation.Services(); ok {
		_spec.SetField(thingmodel.FieldServices, field.TypeJSON, value)
		_node.Services = value
	}
	if value, ok := _c.mutation.Events(); ok {
		_spec.SetField(thingmodel.FieldEvents, field.TypeJSON, value)
		_node.Events = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(thingmodel.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(thingmodel.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(thingmodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(thingmodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thingmodel.TenantTable,
			Columns: []string{thingmodel.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ModelCategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thingmodel.ModelCategoryTable,
			Columns: []string{thingmodel.ModelCategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ModelCategoryID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thingmodel.DevicesTable,
			Columns: []string{thingmodel.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ThingModelCreateBulk is the builder for creating many ThingModel entities in bulk.
type ThingModelCreateBulk struct {
	config
	err      error
	builders []*ThingModelCreate
}

// Save creates the ThingModel entities in the database.
func (_c *ThingModelCreateBulk) Save(ctx context.Context) ([]*ThingModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ThingModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThingModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ThingModelCreateBulk) SaveX(ctx context.Context) []*ThingModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThingModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThingModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
