// Code generated by ent, DO NOT EDIT.

package device

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Seeker32/AssassinIoT/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldID, id))
}

// TenantKey applies equality check predicate on the "tenant_key" field. It's identical to TenantKeyEQ.
func TenantKey(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldTenantKey, v))
}

// ModelKey applies equality check predicate on the "model_key" field. It's identical to ModelKeyEQ.
func ModelKey(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldModelKey, v))
}

// DeviceName applies equality check predicate on the "device_name" field. It's identical to DeviceNameEQ.
func DeviceName(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldDeviceName, v))
}

// AccessKey applies equality check predicate on the "access_key" field. It's identical to AccessKeyEQ.
func AccessKey(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldAccessKey, v))
}

// FirmwareVer applies equality check predicate on the "firmware_ver" field. It's identical to FirmwareVerEQ.
func FirmwareVer(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldFirmwareVer, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldTenantID, v))
}

// ThingModelID applies equality check predicate on the "thing_model_id" field. It's identical to ThingModelIDEQ.
func ThingModelID(v int) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldThingModelID, v))
}

// Online applies equality check predicate on the "online" field. It's identical to OnlineEQ.
func Online(v bool) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldOnline, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastSeen applies equality check predicate on the "last_seen" field. It's identical to LastSeenEQ.
func LastSeen(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldLastSeen, v))
}

// TenantKeyEQ applies the EQ predicate on the "tenant_key" field.
func TenantKeyEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldTenantKey, v))
}

// TenantKeyNEQ applies the NEQ predicate on the "tenant_key" field.
func TenantKeyNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldTenantKey, v))
}

// TenantKeyIn applies the In predicate on the "tenant_key" field.
func TenantKeyIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldTenantKey, vs...))
}

// TenantKeyNotIn applies the NotIn predicate on the "tenant_key" field.
func TenantKeyNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldTenantKey, vs...))
}

// TenantKeyGT applies the GT predicate on the "tenant_key" field.
func TenantKeyGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldTenantKey, v))
}

// TenantKeyGTE applies the GTE predicate on the "tenant_key" field.
func TenantKeyGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldTenantKey, v))
}

// TenantKeyLT applies the LT predicate on the "tenant_key" field.
func TenantKeyLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldTenantKey, v))
}

// TenantKeyLTE applies the LTE predicate on the "tenant_key" field.
func TenantKeyLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldTenantKey, v))
}

// TenantKeyContains applies the Contains predicate on the "tenant_key" field.
func TenantKeyContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldTenantKey, v))
}

// TenantKeyHasPrefix applies the HasPrefix predicate on the "tenant_key" field.
func TenantKeyHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldTenantKey, v))
}

// TenantKeyHasSuffix applies the HasSuffix predicate on the "tenant_key" field.
func TenantKeyHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldTenantKey, v))
}

// TenantKeyEqualFold applies the EqualFold predicate on the "tenant_key" field.
func TenantKeyEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldTenantKey, v))
}

// TenantKeyContainsFold applies the ContainsFold predicate on the "tenant_key" field.
func TenantKeyContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldTenantKey, v))
}

// ModelKeyEQ applies the EQ predicate on the "model_key" field.
func ModelKeyEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldModelKey, v))
}

// ModelKeyNEQ applies the NEQ predicate on the "model_key" field.
func ModelKeyNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldModelKey, v))
}

// ModelKeyIn applies the In predicate on the "model_key" field.
func ModelKeyIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldModelKey, vs...))
}

// ModelKeyNotIn applies the NotIn predicate on the "model_key" field.
func ModelKeyNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldModelKey, vs...))
}

// ModelKeyGT applies the GT predicate on the "model_key" field.
func ModelKeyGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldModelKey, v))
}

// ModelKeyGTE applies the GTE predicate on the "model_key" field.
func ModelKeyGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldModelKey, v))
}

// ModelKeyLT applies the LT predicate on the "model_key" field.
func ModelKeyLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldModelKey, v))
}

// ModelKeyLTE applies the LTE predicate on the "model_key" field.
func ModelKeyLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldModelKey, v))
}

// ModelKeyContains applies the Contains predicate on the "model_key" field.
func ModelKeyContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldModelKey, v))
}

// ModelKeyHasPrefix applies the HasPrefix predicate on the "model_key" field.
func ModelKeyHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldModelKey, v))
}

// ModelKeyHasSuffix applies the HasSuffix predicate on the "model_key" field.
func ModelKeyHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldModelKey, v))
}

// ModelKeyEqualFold applies the EqualFold predicate on the "model_key" field.
func ModelKeyEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldModelKey, v))
}

// ModelKeyContainsFold applies the ContainsFold predicate on the "model_key" field.
func ModelKeyContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldModelKey, v))
}

// DeviceNameEQ applies the EQ predicate on the "device_name" field.
func DeviceNameEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldDeviceName, v))
}

// DeviceNameNEQ applies the NEQ predicate on the "device_name" field.
func DeviceNameNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldDeviceName, v))
}

// DeviceNameIn applies the In predicate on the "device_name" field.
func DeviceNameIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldDeviceName, vs...))
}

// DeviceNameNotIn applies the NotIn predicate on the "device_name" field.
func DeviceNameNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldDeviceName, vs...))
}

// DeviceNameGT applies the GT predicate on the "device_name" field.
func DeviceNameGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldDeviceName, v))
}

// DeviceNameGTE applies the GTE predicate on the "device_name" field.
func DeviceNameGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldDeviceName, v))
}

// DeviceNameLT applies the LT predicate on the "device_name" field.
func DeviceNameLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldDeviceName, v))
}

// DeviceNameLTE applies the LTE predicate on the "device_name" field.
func DeviceNameLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldDeviceName, v))
}

// DeviceNameContains applies the Contains predicate on the "device_name" field.
func DeviceNameContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldDeviceName, v))
}

// DeviceNameHasPrefix applies the HasPrefix predicate on the "device_name" field.
func DeviceNameHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldDeviceName, v))
}

// DeviceNameHasSuffix applies the HasSuffix predicate on the "device_name" field.
func DeviceNameHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldDeviceName, v))
}

// DeviceNameEqualFold applies the EqualFold predicate on the "device_name" field.
func DeviceNameEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldDeviceName, v))
}

// DeviceNameContainsFold applies the ContainsFold predicate on the "device_name" field.
func DeviceNameContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldDeviceName, v))
}

// AccessKeyEQ applies the EQ predicate on the "access_key" field.
func AccessKeyEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldAccessKey, v))
}

// AccessKeyNEQ applies the NEQ predicate on the "access_key" field.
func AccessKeyNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldAccessKey, v))
}

// AccessKeyIn applies the In predicate on the "access_key" field.
func AccessKeyIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldAccessKey, vs...))
}

// AccessKeyNotIn applies the NotIn predicate on the "access_key" field.
func AccessKeyNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldAccessKey, vs...))
}

// AccessKeyGT applies the GT predicate on the "access_key" field.
func AccessKeyGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldAccessKey, v))
}

// AccessKeyGTE applies the GTE predicate on the "access_key" field.
func AccessKeyGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldAccessKey, v))
}

// AccessKeyLT applies the LT predicate on the "access_key" field.
func AccessKeyLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldAccessKey, v))
}

// AccessKeyLTE applies the LTE predicate on the "access_key" field.
func AccessKeyLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldAccessKey, v))
}

// AccessKeyContains applies the Contains predicate on the "access_key" field.
func AccessKeyContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldAccessKey, v))
}

// AccessKeyHasPrefix applies the HasPrefix predicate on the "access_key" field.
func AccessKeyHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldAccessKey, v))
}

// AccessKeyHasSuffix applies the HasSuffix predicate on the "access_key" field.
func AccessKeyHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldAccessKey, v))
}

// AccessKeyEqualFold applies the EqualFold predicate on the "access_key" field.
func AccessKeyEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldAccessKey, v))
}

// AccessKeyContainsFold applies the ContainsFold predicate on the "access_key" field.
func AccessKeyContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldAccessKey, v))
}

// FirmwareVerEQ applies the EQ predicate on the "firmware_ver" field.
func FirmwareVerEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldFirmwareVer, v))
}

// FirmwareVerNEQ applies the NEQ predicate on the "firmware_ver" field.
func FirmwareVerNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldFirmwareVer, v))
}

// FirmwareVerIn applies the In predicate on the "firmware_ver" field.
func FirmwareVerIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldFirmwareVer, vs...))
}

// FirmwareVerNotIn applies the NotIn predicate on the "firmware_ver" field.
func FirmwareVerNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldFirmwareVer, vs...))
}

// FirmwareVerGT applies the GT predicate on the "firmware_ver" field.
func FirmwareVerGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldFirmwareVer, v))
}

// FirmwareVerGTE applies the GTE predicate on the "firmware_ver" field.
func FirmwareVerGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldFirmwareVer, v))
}

// FirmwareVerLT applies the LT predicate on the "firmware_ver" field.
func FirmwareVerLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldFirmwareVer, v))
}

// FirmwareVerLTE applies the LTE predicate on the "firmware_ver" field.
func FirmwareVerLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldFirmwareVer, v))
}

// FirmwareVerContains applies the Contains predicate on the "firmware_ver" field.
func FirmwareVerContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldFirmwareVer, v))
}

// FirmwareVerHasPrefix applies the HasPrefix predicate on the "firmware_ver" field.
func FirmwareVerHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldFirmwareVer, v))
}

// FirmwareVerHasSuffix applies the HasSuffix predicate on the "firmware_ver" field.
func FirmwareVerHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldFirmwareVer, v))
}

// FirmwareVerEqualFold applies the EqualFold predicate on the "firmware_ver" field.
func FirmwareVerEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldFirmwareVer, v))
}

// FirmwareVerContainsFold applies the ContainsFold predicate on the "firmware_ver" field.
func FirmwareVerContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldFirmwareVer, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldTenantID, vs...))
}

// ThingModelIDEQ applies the EQ predicate on the "thing_model_id" field.
func ThingModelIDEQ(v int) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldThingModelID, v))
}

// ThingModelIDNEQ applies the NEQ predicate on the "thing_model_id" field.
func ThingModelIDNEQ(v int) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldThingModelID, v))
}

// ThingModelIDIn applies the In predicate on the "thing_model_id" field.
func ThingModelIDIn(vs ...int) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldThingModelID, vs...))
}

// ThingModelIDNotIn applies the NotIn predicate on the "thing_model_id" field.
func ThingModelIDNotIn(vs ...int) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldThingModelID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldStatus, vs...))
}

// OnlineEQ applies the EQ predicate on the "online" field.
func OnlineEQ(v bool) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldOnline, v))
}

// OnlineNEQ applies the NEQ predicate on the "online" field.
func OnlineNEQ(v bool) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldOnline, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastSeenEQ applies the EQ predicate on the "last_seen" field.
func LastSeenEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldLastSeen, v))
}

// LastSeenNEQ applies the NEQ predicate on the "last_seen" field.
func LastSeenNEQ(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldLastSeen, v))
}

// LastSeenIn applies the In predicate on the "last_seen" field.
func LastSeenIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldLastSeen, vs...))
}

// LastSeenNotIn applies the NotIn predicate on the "last_seen" field.
func LastSeenNotIn(vs ...time.Time) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldLastSeen, vs...))
}

// LastSeenGT applies the GT predicate on the "last_seen" field.
func LastSeenGT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldLastSeen, v))
}

// LastSeenGTE applies the GTE predicate on the "last_seen" field.
func LastSeenGTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldLastSeen, v))
}

// LastSeenLT applies the LT predicate on the "last_seen" field.
func LastSeenLT(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldLastSeen, v))
}

// LastSeenLTE applies the LTE predicate on the "last_seen" field.
func LastSeenLTE(v time.Time) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldLastSeen, v))
}

// LastSeenIsNil applies the IsNil predicate on the "last_seen" field.
func LastSeenIsNil() predicate.Device {
	return predicate.Device(sql.FieldIsNull(FieldLastSeen))
}

// LastSeenNotNil applies the NotNil predicate on the "last_seen" field.
func LastSeenNotNil() predicate.Device {
	return predicate.Device(sql.FieldNotNull(FieldLastSeen))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Device {
	return predicate.Device(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Device {
	return predicate.Device(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasThingModel applies the HasEdge predicate on the "thing_model" edge.
func HasThingModel() predicate.Device {
	return predicate.Device(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ThingModelTable, ThingModelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasThingModelWith applies the HasEdge predicate on the "thing_model" edge with a given conditions (other predicates).
func HasThingModelWith(preds ...predicate.ThingModel) predicate.Device {
	return predicate.Device(func(s *sql.Selector) {
		step := newThingModelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Device) predicate.Device {
	return predicate.Device(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Device) predicate.Device {
	return predicate.Device(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Device) predicate.Device {
	return predicate.Device(sql.NotPredicates(p))
}
