node {
  name = "emqx@127.0.0.1"
  cookie = "assassin-iot-secret"
  data_dir = "/opt/emqx/data"
  db_backend = "rlog"
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 102400
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
}

listeners.ssl.default {
  enabled = false
}

listeners.wss.default {
  enabled = false
}

dashboard {
  listeners.http {
    bind = "0.0.0.0:18083"
  }
  default_username = "admin"
  default_password = "public"
}

authorization {
  no_match = deny
  sources = [
    {
      type = "file"
      enable = true
      path = "/opt/emqx/etc/acl.conf"
    }
  ]
}
