// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AssassinIoT/ent/device"
	"AssassinIoT/ent/modelcategory"
	"AssassinIoT/ent/predicate"
	"AssassinIoT/ent/tenant"
	"AssassinIoT/ent/thingmodel"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantKey sets the "tenant_key" field.
func (_u *TenantUpdate) SetTenantKey(v string) *TenantUpdate {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableTenantKey(v *string) *TenantUpdate {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TenantUpdate) SetDescription(v string) *TenantUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableDescription(v *string) *TenantUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdate) SetStatus(v tenant.Status) *TenantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableStatus(v *tenant.Status) *TenantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdate) SetUpdatedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddModelCategoryIDs adds the "model_categories" edge to the ModelCategory entity by IDs.
func (_u *TenantUpdate) AddModelCategoryIDs(ids ...int) *TenantUpdate {
	_u.mutation.AddModelCategoryIDs(ids...)
	return _u
}

// AddModelCategories adds the "model_categories" edges to the ModelCategory entity.
func (_u *TenantUpdate) AddModelCategories(v ...*ModelCategory) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelCategoryIDs(ids...)
}

// AddThingModelIDs adds the "thing_models" edge to the ThingModel entity by IDs.
func (_u *TenantUpdate) AddThingModelIDs(ids ...int) *TenantUpdate {
	_u.mutation.AddThingModelIDs(ids...)
	return _u
}

// AddThingModels adds the "thing_models" edges to the ThingModel entity.
func (_u *TenantUpdate) AddThingModels(v ...*ThingModel) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddThingModelIDs(ids...)
}

// AddDeviceIDs adds the "devices" edge to the Device entity by IDs.
func (_u *TenantUpdate) AddDeviceIDs(ids ...string) *TenantUpdate {
	_u.mutation.AddDeviceIDs(ids...)
	return _u
}

// AddDevices adds the "devices" edges to the Device entity.
func (_u *TenantUpdate) AddDevices(v ...*Device) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeviceIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearModelCategories clears all "model_categories" edges to the ModelCategory entity.
func (_u *TenantUpdate) ClearModelCategories() *TenantUpdate {
	_u.mutation.ClearModelCategories()
	return _u
}

// RemoveModelCategoryIDs removes the "model_categories" edge to ModelCategory entities by IDs.
func (_u *TenantUpdate) RemoveModelCategoryIDs(ids ...int) *TenantUpdate {
	_u.mutation.RemoveModelCategoryIDs(ids...)
	return _u
}

// RemoveModelCategories removes "model_categories" edges to ModelCategory entities.
func (_u *TenantUpdate) RemoveModelCategories(v ...*ModelCategory) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelCategoryIDs(ids...)
}

// ClearThingModels clears all "thing_models" edges to the ThingModel entity.
func (_u *TenantUpdate) ClearThingModels() *TenantUpdate {
	_u.mutation.ClearThingModels()
	return _u
}

// RemoveThingModelIDs removes the "thing_models" edge to ThingModel entities by IDs.
func (_u *TenantUpdate) RemoveThingModelIDs(ids ...int) *TenantUpdate {
	_u.mutation.RemoveThingModelIDs(ids...)
	return _u
}

// RemoveThingModels removes "thing_models" edges to ThingModel entities.
func (_u *TenantUpdate) RemoveThingModels(v ...*ThingModel) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveThingModelIDs(ids...)
}

// ClearDevices clears all "devices" edges to the Device entity.
func (_u *TenantUpdate) ClearDevices() *TenantUpdate {
	_u.mutation.ClearDevices()
	return _u
}

// RemoveDeviceIDs removes the "devices" edge to Device entities by IDs.
func (_u *TenantUpdate) RemoveDeviceIDs(ids ...string) *TenantUpdate {
	_u.mutation.RemoveDeviceIDs(ids...)
	return _u
}

// RemoveDevices removes "devices" edges to Device entities.
func (_u *TenantUpdate) RemoveDevices(v ...*Device) *TenantUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeviceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdate) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := tenant.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`ent: validator failed for field "Tenant.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tenant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Tenant.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(tenant.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tenant.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ModelCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ModelCategoriesTable,
			Columns: []string{tenant.ModelCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcategory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelCategoriesIDs(); len(nodes) > 0 && !_u.mutation.ModelCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ModelCategoriesTable,
			Columns: []string{tenant.ModelCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelCategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ModelCategoriesTable,
			Columns: []string{tenant.ModelCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThingModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ThingModelsTable,
			Columns: []string{tenant.ThingModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedThingModelsIDs(); len(nodes) > 0 && !_u.mutation.ThingModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ThingModelsTable,
			Columns: []string{tenant.ThingModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThingModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ThingModelsTable,
			Columns: []string{tenant.ThingModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DevicesTable,
			Columns: []string{tenant.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDevicesIDs(); len(nodes) > 0 && !_u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DevicesTable,
			Columns: []string{tenant.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DevicesTable,
			Columns: []string{tenant.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetTenantKey sets the "tenant_key" field.
func (_u *TenantUpdateOne) SetTenantKey(v string) *TenantUpdateOne {
	_u.mutation.SetTenantKey(v)
	return _u
}

// SetNillableTenantKey sets the "tenant_key" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableTenantKey(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetTenantKey(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TenantUpdateOne) SetDescription(v string) *TenantUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableDescription(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdateOne) SetStatus(v tenant.Status) *TenantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableStatus(v *tenant.Status) *TenantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdateOne) SetUpdatedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddModelCategoryIDs adds the "model_categories" edge to the ModelCategory entity by IDs.
func (_u *TenantUpdateOne) AddModelCategoryIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.AddModelCategoryIDs(ids...)
	return _u
}

// AddModelCategories adds the "model_categories" edges to the ModelCategory entity.
func (_u *TenantUpdateOne) AddModelCategories(v ...*ModelCategory) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelCategoryIDs(ids...)
}

// AddThingModelIDs adds the "thing_models" edge to the ThingModel entity by IDs.
func (_u *TenantUpdateOne) AddThingModelIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.AddThingModelIDs(ids...)
	return _u
}

// AddThingModels adds the "thing_models" edges to the ThingModel entity.
func (_u *TenantUpdateOne) AddThingModels(v ...*ThingModel) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddThingModelIDs(ids...)
}

// AddDeviceIDs adds the "devices" edge to the Device entity by IDs.
func (_u *TenantUpdateOne) AddDeviceIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.AddDeviceIDs(ids...)
	return _u
}

// AddDevices adds the "devices" edges to the Device entity.
func (_u *TenantUpdateOne) AddDevices(v ...*Device) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeviceIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearModelCategories clears all "model_categories" edges to the ModelCategory entity.
func (_u *TenantUpdateOne) ClearModelCategories() *TenantUpdateOne {
	_u.mutation.ClearModelCategories()
	return _u
}

// RemoveModelCategoryIDs removes the "model_categories" edge to ModelCategory entities by IDs.
func (_u *TenantUpdateOne) RemoveModelCategoryIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.RemoveModelCategoryIDs(ids...)
	return _u
}

// RemoveModelCategories removes "model_categories" edges to ModelCategory entities.
func (_u *TenantUpdateOne) RemoveModelCategories(v ...*ModelCategory) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelCategoryIDs(ids...)
}

// ClearThingModels clears all "thing_models" edges to the ThingModel entity.
func (_u *TenantUpdateOne) ClearThingModels() *TenantUpdateOne {
	_u.mutation.ClearThingModels()
	return _u
}

// RemoveThingModelIDs removes the "thing_models" edge to ThingModel entities by IDs.
func (_u *TenantUpdateOne) RemoveThingModelIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.RemoveThingModelIDs(ids...)
	return _u
}

// RemoveThingModels removes "thing_models" edges to ThingModel entities.
func (_u *TenantUpdateOne) RemoveThingModels(v ...*ThingModel) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveThingModelIDs(ids...)
}

// ClearDevices clears all "devices" edges to the Device entity.
func (_u *TenantUpdateOne) ClearDevices() *TenantUpdateOne {
	_u.mutation.ClearDevices()
	return _u
}

// RemoveDeviceIDs removes the "devices" edge to Device entities by IDs.
func (_u *TenantUpdateOne) RemoveDeviceIDs(ids ...string) *TenantUpdateOne {
	_u.mutation.RemoveDeviceIDs(ids...)
	return _u
}

// RemoveDevices removes "devices" edges to Device entities.
func (_u *TenantUpdateOne) RemoveDevices(v ...*Device) *TenantUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeviceIDs(ids...)
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdateOne) check() error {
	if v, ok := _u.mutation.TenantKey(); ok {
		if err := tenant.TenantKeyValidator(v); err != nil {
			return &ValidationError{Name: "tenant_key", err: fmt.Errorf(`ent: validator failed for field "Tenant.tenant_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tenant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Tenant.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantKey(); ok {
		_spec.SetField(tenant.FieldTenantKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tenant.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ModelCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ModelCategoriesTable,
			Columns: []string{tenant.ModelCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcategory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelCategoriesIDs(); len(nodes) > 0 && !_u.mutation.ModelCategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ModelCategoriesTable,
			Columns: []string{tenant.ModelCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelCategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ModelCategoriesTable,
			Columns: []string{tenant.ModelCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ThingModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ThingModelsTable,
			Columns: []string{tenant.ThingModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedThingModelsIDs(); len(nodes) > 0 && !_u.mutation.ThingModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ThingModelsTable,
			Columns: []string{tenant.ThingModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ThingModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.ThingModelsTable,
			Columns: []string{tenant.ThingModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thingmodel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DevicesTable,
			Columns: []string{tenant.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDevicesIDs(); len(nodes) > 0 && !_u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DevicesTable,
			Columns: []string{tenant.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.DevicesTable,
			Columns: []string{tenant.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
