// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "dev_id", Type: field.TypeString},
		{Name: "tenant_key", Type: field.TypeString, Size: 64},
		{Name: "model_key", Type: field.TypeString, Size: 64},
		{Name: "device_name", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "access_key", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "firmware_ver", Type: field.TypeString, Size: 32, Default: ""},
		{Name: "properties_cfg", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "disabled"}, Default: "active"},
		{Name: "online", Type: field.TypeBool, Default: false},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_seen", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "thing_model_id", Type: field.TypeInt},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "devices_tenants_devices",
				Columns:    []*schema.Column{DevicesColumns[13]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "devices_thing_models_devices",
				Columns:    []*schema.Column{DevicesColumns[14]},
				RefColumns: []*schema.Column{ThingModelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "device_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[1]},
			},
			{
				Name:    "device_tenant_key_model_key",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[1], DevicesColumns[2]},
			},
			{
				Name:    "device_status",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[7]},
			},
			{
				Name:    "device_tenant_key_status",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[1], DevicesColumns[7]},
			},
		},
	}
	// ModelCategoriesColumns holds the columns for the "model_categories" table.
	ModelCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 64},
		{Name: "category_key", Type: field.TypeString, Size: 64},
		{Name: "display_name", Type: field.TypeString, Size: 128},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "icon", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// ModelCategoriesTable holds the schema information for the "model_categories" table.
	ModelCategoriesTable = &schema.Table{
		Name:       "model_categories",
		Columns:    ModelCategoriesColumns,
		PrimaryKey: []*schema.Column{ModelCategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "model_categories_tenants_model_categories",
				Columns:    []*schema.Column{ModelCategoriesColumns[10]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "modelcategory_tenant_key_category_key",
				Unique:  true,
				Columns: []*schema.Column{ModelCategoriesColumns[1], ModelCategoriesColumns[2]},
			},
			{
				Name:    "modelcategory_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{ModelCategoriesColumns[1]},
			},
			{
				Name:    "modelcategory_tenant_key_sort_order",
				Unique:  false,
				Columns: []*schema.Column{ModelCategoriesColumns[1], ModelCategoriesColumns[6]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tenant_key", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tenant_tenant_key",
				Unique:  true,
				Columns: []*schema.Column{TenantsColumns[1]},
			},
		},
	}
	// ThingModelsColumns holds the columns for the "thing_models" table.
	ThingModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "model_key", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "tenant_key", Type: field.TypeString, Size: 64},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "category", Type: field.TypeString, Size: 64},
		{Name: "properties", Type: field.TypeJSON},
		{Name: "services", Type: field.TypeJSON},
		{Name: "events", Type: field.TypeJSON},
		{Name: "version", Type: field.TypeString, Size: 16, Default: "1.0"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "deprecated", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "model_category_id", Type: field.TypeInt},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// ThingModelsTable holds the schema information for the "thing_models" table.
	ThingModelsTable = &schema.Table{
		Name:       "thing_models",
		Columns:    ThingModelsColumns,
		PrimaryKey: []*schema.Column{ThingModelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "thing_models_model_categories_thing_models",
				Columns:    []*schema.Column{ThingModelsColumns[13]},
				RefColumns: []*schema.Column{ModelCategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "thing_models_tenants_thing_models",
				Columns:    []*schema.Column{ThingModelsColumns[14]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "thingmodel_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{ThingModelsColumns[2]},
			},
			{
				Name:    "thingmodel_tenant_key_category",
				Unique:  false,
				Columns: []*schema.Column{ThingModelsColumns[2], ThingModelsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DevicesTable,
		ModelCategoriesTable,
		TenantsTable,
		ThingModelsTable,
	}
)

func init() {
	DevicesTable.ForeignKeys[0].RefTable = TenantsTable
	DevicesTable.ForeignKeys[1].RefTable = ThingModelsTable
	DevicesTable.Annotation = &entsql.Annotation{
		Table: "devices",
	}
	ModelCategoriesTable.ForeignKeys[0].RefTable = TenantsTable
	ModelCategoriesTable.Annotation = &entsql.Annotation{
		Table: "model_categories",
	}
	TenantsTable.Annotation = &entsql.Annotation{
		Table: "tenants",
	}
	ThingModelsTable.ForeignKeys[0].RefTable = ModelCategoriesTable
	ThingModelsTable.ForeignKeys[1].RefTable = TenantsTable
	ThingModelsTable.Annotation = &entsql.Annotation{
		Table: "thing_models",
	}
}
