// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "avatar_url", Type: field.TypeString},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "account_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[6]},
			},
			{
				Name:    "account_email",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[4]},
			},
			{
				Name:    "account_username",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[2]},
			},
			{
				Name:    "account_tenant_id_email",
				Unique:  true,
				Columns: []*schema.Column{AccountsColumns[6], AccountsColumns[4]},
			},
		},
	}
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 64},
		{Name: "model_key", Type: field.TypeString, Size: 64},
		{Name: "device_name", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "access_key", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "firmware_ver", Type: field.TypeString, Size: 32, Default: ""},
		{Name: "properties_cfg", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "inactive", "disabled"}, Default: "active"},
		{Name: "online", Type: field.TypeBool, Default: false},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_seen", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "thing_model_id", Type: field.TypeInt},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "devices_tenants_devices",
				Columns:    []*schema.Column{DevicesColumns[14]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "devices_thing_models_devices",
				Columns:    []*schema.Column{DevicesColumns[15]},
				RefColumns: []*schema.Column{ThingModelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "device_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[2]},
			},
			{
				Name:    "device_tenant_key_model_key",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[2], DevicesColumns[3]},
			},
			{
				Name:    "device_status",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[8]},
			},
			{
				Name:    "device_tenant_key_status",
				Unique:  false,
				Columns: []*schema.Column{DevicesColumns[2], DevicesColumns[8]},
			},
		},
	}
	// ModelCategoriesColumns holds the columns for the "model_categories" table.
	ModelCategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_key", Type: field.TypeString, Size: 64},
		{Name: "category_key", Type: field.TypeString, Size: 64},
		{Name: "display_name", Type: field.TypeString, Size: 128},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "icon", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// ModelCategoriesTable holds the schema information for the "model_categories" table.
	ModelCategoriesTable = &schema.Table{
		Name:       "model_categories",
		Columns:    ModelCategoriesColumns,
		PrimaryKey: []*schema.Column{ModelCategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "model_categories_tenants_model_categories",
				Columns:    []*schema.Column{ModelCategoriesColumns[11]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "modelcategory_tenant_key_category_key",
				Unique:  true,
				Columns: []*schema.Column{ModelCategoriesColumns[2], ModelCategoriesColumns[3]},
			},
			{
				Name:    "modelcategory_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{ModelCategoriesColumns[2]},
			},
			{
				Name:    "modelcategory_tenant_key_sort_order",
				Unique:  false,
				Columns: []*schema.Column{ModelCategoriesColumns[2], ModelCategoriesColumns[7]},
			},
		},
	}
	// MqttUserColumns holds the columns for the "mqtt_user" table.
	MqttUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "password_hash", Type: field.TypeString, Size: 256},
		{Name: "salt", Type: field.TypeString, Size: 64},
		{Name: "is_superuser", Type: field.TypeBool, Default: false},
		{Name: "created", Type: field.TypeTime},
	}
	// MqttUserTable holds the schema information for the "mqtt_user" table.
	MqttUserTable = &schema.Table{
		Name:       "mqtt_user",
		Columns:    MqttUserColumns,
		PrimaryKey: []*schema.Column{MqttUserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mqttuser_username",
				Unique:  true,
				Columns: []*schema.Column{MqttUserColumns[2]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_key", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tenant_tenant_key",
				Unique:  true,
				Columns: []*schema.Column{TenantsColumns[2]},
			},
		},
	}
	// ThingModelsColumns holds the columns for the "thing_models" table.
	ThingModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "model_key", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "tenant_key", Type: field.TypeString, Size: 64},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "category", Type: field.TypeString, Size: 64},
		{Name: "properties", Type: field.TypeJSON},
		{Name: "services", Type: field.TypeJSON},
		{Name: "events", Type: field.TypeJSON},
		{Name: "version", Type: field.TypeString, Size: 16, Default: "1.0"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "deprecated", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "model_category_id", Type: field.TypeInt},
		{Name: "tenant_id", Type: field.TypeInt},
	}
	// ThingModelsTable holds the schema information for the "thing_models" table.
	ThingModelsTable = &schema.Table{
		Name:       "thing_models",
		Columns:    ThingModelsColumns,
		PrimaryKey: []*schema.Column{ThingModelsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "thing_models_model_categories_thing_models",
				Columns:    []*schema.Column{ThingModelsColumns[14]},
				RefColumns: []*schema.Column{ModelCategoriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "thing_models_tenants_thing_models",
				Columns:    []*schema.Column{ThingModelsColumns[15]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "thingmodel_tenant_key",
				Unique:  false,
				Columns: []*schema.Column{ThingModelsColumns[3]},
			},
			{
				Name:    "thingmodel_tenant_key_category",
				Unique:  false,
				Columns: []*schema.Column{ThingModelsColumns[3], ThingModelsColumns[6]},
			},
		},
	}
	// TenantAccountsColumns holds the columns for the "tenant_accounts" table.
	TenantAccountsColumns = []*schema.Column{
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "account_id", Type: field.TypeInt},
	}
	// TenantAccountsTable holds the schema information for the "tenant_accounts" table.
	TenantAccountsTable = &schema.Table{
		Name:       "tenant_accounts",
		Columns:    TenantAccountsColumns,
		PrimaryKey: []*schema.Column{TenantAccountsColumns[0], TenantAccountsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tenant_accounts_tenant_id",
				Columns:    []*schema.Column{TenantAccountsColumns[0]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tenant_accounts_account_id",
				Columns:    []*schema.Column{TenantAccountsColumns[1]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		DevicesTable,
		ModelCategoriesTable,
		MqttUserTable,
		TenantsTable,
		ThingModelsTable,
		TenantAccountsTable,
	}
)

func init() {
	AccountsTable.Annotation = &entsql.Annotation{
		Table: "accounts",
	}
	DevicesTable.ForeignKeys[0].RefTable = TenantsTable
	DevicesTable.ForeignKeys[1].RefTable = ThingModelsTable
	DevicesTable.Annotation = &entsql.Annotation{
		Table: "devices",
	}
	ModelCategoriesTable.ForeignKeys[0].RefTable = TenantsTable
	ModelCategoriesTable.Annotation = &entsql.Annotation{
		Table: "model_categories",
	}
	MqttUserTable.Annotation = &entsql.Annotation{
		Table: "mqtt_user",
	}
	TenantsTable.Annotation = &entsql.Annotation{
		Table: "tenants",
	}
	ThingModelsTable.ForeignKeys[0].RefTable = ModelCategoriesTable
	ThingModelsTable.ForeignKeys[1].RefTable = TenantsTable
	ThingModelsTable.Annotation = &entsql.Annotation{
		Table: "thing_models",
	}
	TenantAccountsTable.ForeignKeys[0].RefTable = TenantsTable
	TenantAccountsTable.ForeignKeys[1].RefTable = AccountsTable
}
