// Code generated by ent, DO NOT EDIT.

package device

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the device type in the database.
	Label = "device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "dev_id"
	// FieldTenantKey holds the string denoting the tenant_key field in the database.
	FieldTenantKey = "tenant_key"
	// FieldModelKey holds the string denoting the model_key field in the database.
	FieldModelKey = "model_key"
	// FieldDeviceName holds the string denoting the device_name field in the database.
	FieldDeviceName = "device_name"
	// FieldAccessKey holds the string denoting the access_key field in the database.
	FieldAccessKey = "access_key"
	// FieldFirmwareVer holds the string denoting the firmware_ver field in the database.
	FieldFirmwareVer = "firmware_ver"
	// FieldPropertiesCfg holds the string denoting the properties_cfg field in the database.
	FieldPropertiesCfg = "properties_cfg"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldThingModelID holds the string denoting the thing_model_id field in the database.
	FieldThingModelID = "thing_model_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldOnline holds the string denoting the online field in the database.
	FieldOnline = "online"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldLastSeen holds the string denoting the last_seen field in the database.
	FieldLastSeen = "last_seen"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeThingModel holds the string denoting the thing_model edge name in mutations.
	EdgeThingModel = "thing_model"
	// TenantFieldID holds the string denoting the ID field of the Tenant.
	TenantFieldID = "id"
	// ThingModelFieldID holds the string denoting the ID field of the ThingModel.
	ThingModelFieldID = "id"
	// Table holds the table name of the device in the database.
	Table = "devices"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "devices"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// ThingModelTable is the table that holds the thing_model relation/edge.
	ThingModelTable = "devices"
	// ThingModelInverseTable is the table name for the ThingModel entity.
	// It exists in this package in order to avoid circular dependency with the "thingmodel" package.
	ThingModelInverseTable = "thing_models"
	// ThingModelColumn is the table column denoting the thing_model relation/edge.
	ThingModelColumn = "thing_model_id"
)

// Columns holds all SQL columns for device fields.
var Columns = []string{
	FieldID,
	FieldTenantKey,
	FieldModelKey,
	FieldDeviceName,
	FieldAccessKey,
	FieldFirmwareVer,
	FieldPropertiesCfg,
	FieldTenantID,
	FieldThingModelID,
	FieldStatus,
	FieldOnline,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldLastSeen,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantKeyValidator is a validator for the "tenant_key" field. It is called by the builders before save.
	TenantKeyValidator func(string) error
	// ModelKeyValidator is a validator for the "model_key" field. It is called by the builders before save.
	ModelKeyValidator func(string) error
	// DefaultDeviceName holds the default value on creation for the "device_name" field.
	DefaultDeviceName string
	// DeviceNameValidator is a validator for the "device_name" field. It is called by the builders before save.
	DeviceNameValidator func(string) error
	// AccessKeyValidator is a validator for the "access_key" field. It is called by the builders before save.
	AccessKeyValidator func(string) error
	// DefaultFirmwareVer holds the default value on creation for the "firmware_ver" field.
	DefaultFirmwareVer string
	// FirmwareVerValidator is a validator for the "firmware_ver" field. It is called by the builders before save.
	FirmwareVerValidator func(string) error
	// DefaultPropertiesCfg holds the default value on creation for the "properties_cfg" field.
	DefaultPropertiesCfg map[string]interface{}
	// DefaultOnline holds the default value on creation for the "online" field.
	DefaultOnline bool
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusInactive Status = "inactive"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("device: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Device queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantKey orders the results by the tenant_key field.
func ByTenantKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantKey, opts...).ToFunc()
}

// ByModelKey orders the results by the model_key field.
func ByModelKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelKey, opts...).ToFunc()
}

// ByDeviceName orders the results by the device_name field.
func ByDeviceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceName, opts...).ToFunc()
}

// ByAccessKey orders the results by the access_key field.
func ByAccessKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessKey, opts...).ToFunc()
}

// ByFirmwareVer orders the results by the firmware_ver field.
func ByFirmwareVer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirmwareVer, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByThingModelID orders the results by the thing_model_id field.
func ByThingModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThingModelID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByOnline orders the results by the online field.
func ByOnline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOnline, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByLastSeen orders the results by the last_seen field.
func ByLastSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeen, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByThingModelField orders the results by thing_model field.
func ByThingModelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newThingModelStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, TenantFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newThingModelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ThingModelInverseTable, ThingModelFieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ThingModelTable, ThingModelColumn),
	)
}
